
"use strict";
var logGenerator = require("../../helpers/logGenerator.js"),
    logger = logGenerator.getApplicationLogger(),
    dashboardPage = require('../pageObjects/dashboard.pageObject.js'),
    launchpadPage = require('../pageObjects/launchpad.pageObject.js'),
    delivery_insights = require('../pageObjects/delivery_insights.pageObject.js'),
    launchpadTestData = require('../../testData/cards/launchpadTestData.json'),
	dashboardTestData = require('../../testData/cards/dashboardTestData.json'),
	deliveryInsightTestData = require('../../testData/cards/deliveryInsightsTestData.json'),
    appUrls = require('../../testData/appUrls.json'),
    esQueriesDelivery = require('../../elasticSearchTool/esQuery_DeliveryPayload.js'),
    util = require('../../helpers/util.js'),
    tenantId = browser.params.tenantId,
    frames = require('../../testData/frames.json'),
	applicationUrl = browser.params.url,
	isEnabledESValidation = browser.params.esValidation;

describe('Delivery Insights - functionality ', function () {
    var dashboardObj, launchpadObj, deliveryInsightObj;

        beforeAll(function() {
            dashboardObj = new dashboardPage();
            launchpadObj = new launchpadPage();
            deliveryInsightObj = new delivery_insights();
            browser.driver.manage().window().maximize();
        });

        beforeEach(function() {
            launchpadObj.open();
            launchpadObj.clickOnHamburgerMenu(launchpadTestData.leftNavigationExpanded);
            launchpadObj.clickOnleftNavigationMenuBasedOnName(launchpadTestData.aIOpsIntelligentITOperationsBtn);
            launchpadObj.clickLeftNavCardBasedOnName(launchpadTestData.dashboardCard);
            dashboardObj.open();
        });

        /*Start -- Automation Summary Action Plan Page Validation*/

        it('verify Delivery Insights data card Automation Summary Action Plans table link is clickable and redirect to respective page', function() {
            dashboardObj.clickDeliveryInsightLink(deliveryInsightTestData.eSAsapDashboardName);
            expect(deliveryInsightObj.getDeliveryInsightAutoGeneratedTicketsFlowingText()).toEqual(deliveryInsightTestData.eSAsapClickableTc);
		});

        if(isEnabledESValidation){
			it('verify Automation Summary Action Plan page - check for total count for action plan 101', async function(){
				var year_month = await util.getMonthAndYear();
				var TotalTicketCountFromES =  await esQueriesDelivery.getTotalTicketCount(deliveryInsightTestData.eSActionPlanSearchIndex,tenantId,year_month,101);
				await dashboardObj.clickDeliveryInsightLink(deliveryInsightTestData.eSAsapDashboardName);
				var totalTicketCountFromPage = await deliveryInsightObj.getDeliveryInsightActionPlanTotalTicketCount(deliveryInsightTestData.eSAsapWidgetTotalTickets);
				var totalTicketCountFromPageIntVal = util.stringToInteger(totalTicketCountFromPage);
				expect(totalTicketCountFromPageIntVal).toEqual(TotalTicketCountFromES);
			});

			it('verify Automation Summary Action Plan page - check for total count for action plan 102', async function(){
				var year_month = await util.getMonthAndYear();
				var TotalTicketCountFromES =  await esQueriesDelivery.getTotalTicketCount(deliveryInsightTestData.eSActionPlanSearchIndex,tenantId,year_month,102);
				await dashboardObj.clickDeliveryInsightLink(deliveryInsightTestData.eSAsapDashboardName);
				var totalTicketCountFromPage = await deliveryInsightObj.getDeliveryInsightActionPlanEnhancedTablesTicketCount(deliveryInsightTestData.eSAsapCerWidget);
				var totalTicketCountFromPageIntVal = util.stringToInteger(totalTicketCountFromPage);
				expect(totalTicketCountFromPageIntVal).toEqual(TotalTicketCountFromES);
			});

			it('verify Automation Summary Action Plan page - check for total count for action plan 103', async function(){
				var year_month = await util.getMonthAndYear();
				var TotalTicketCountFromES =  await esQueriesDelivery.getTotalTicketCount(deliveryInsightTestData.eSActionPlanSearchIndex,tenantId,year_month,103);
				await dashboardObj.clickDeliveryInsightLink(deliveryInsightTestData.eSAsapDashboardName);
				var totalTicketCountFromPage = await deliveryInsightObj.getDeliveryInsightActionPlanEnhancedTablesTicketCount(deliveryInsightTestData.eSAsapTberWidget);
				var totalTicketCountFromPageIntVal = util.stringToInteger(totalTicketCountFromPage);
				expect(totalTicketCountFromPageIntVal).toEqual(TotalTicketCountFromES);
			});

			it('verify Automation Summary Action Plan page - check for total count for action plan 104', async function(){
				var year_month = await util.getMonthAndYear();
				var TotalTicketCountFromES =  await esQueriesDelivery.getTotalTicketCount(deliveryInsightTestData.eSActionPlanSearchIndex,tenantId,year_month,104);
				await dashboardObj.clickDeliveryInsightLink(deliveryInsightTestData.eSAsapDashboardName);
				var totalTicketCountFromPage = await deliveryInsightObj.getDeliveryInsightActionPlanEnhancedTablesTicketCount(deliveryInsightTestData.eSAsapClickableTc);
				var totalTicketCountFromPageIntVal = util.stringToInteger(totalTicketCountFromPage);
				expect(totalTicketCountFromPageIntVal).toEqual(TotalTicketCountFromES);
			});

			it('verify Automation Summary Action Plan page - check for total count for action plan 105', async function(){
				var year_month = await util.getMonthAndYear();
				var TotalTicketCountFromES =  await esQueriesDelivery.getTotalTicketCount(deliveryInsightTestData.eSActionPlanSearchIndex,tenantId,year_month,105);
				await dashboardObj.clickDeliveryInsightLink(deliveryInsightTestData.eSAsapDashboardName);
				var totalTicketCountFromPage = await deliveryInsightObj.getDeliveryInsightActionPlanEnhancedTablesTicketCount(deliveryInsightTestData.eSAENotFlow);
				var totalTicketCountFromPageIntVal = util.stringToInteger(totalTicketCountFromPage);
				expect(totalTicketCountFromPageIntVal).toEqual(TotalTicketCountFromES);
			});

			it('verify Automation Summary Action Plan page - check for total count for action plan 106', async function(){
				var year_month = await util.getMonthAndYear();
				var TotalTicketCountFromES =  await esQueriesDelivery.getTotalTicketCount(deliveryInsightTestData.eSActionPlanSearchIndex,tenantId,year_month,106);
				dashboardObj.clickDeliveryInsightLink(deliveryInsightTestData.eSAsapDashboardName);
				var totalTicketCountFromPage = await deliveryInsightObj.getDeliveryInsightActionPlanEnhancedTablesTicketCount(deliveryInsightTestData.eSManualTickets);
				var totalTicketCountFromPageIntVal = util.stringToInteger(totalTicketCountFromPage);
				expect(totalTicketCountFromPageIntVal).toEqual(TotalTicketCountFromES);
			});

			it('verify Automation Summary Action Plan page - check for total count for action plan 107', async function(){
				var year_month = await util.getMonthAndYear();
				var TotalTicketCountFromES =  await esQueriesDelivery.getTotalTicketCount(deliveryInsightTestData.eSActionPlanSearchIndex,tenantId,year_month,107);
				dashboardObj.clickDeliveryInsightLink(deliveryInsightTestData.eSAsapDashboardName);
				var totalTicketCountFromPage = await deliveryInsightObj.getDeliveryInsightActionPlanIdCount(deliveryInsightTestData.eSAsapFailedTickets);
				var totalTicketCountFromPageIntVal = util.stringToInteger(totalTicketCountFromPage);
				expect(totalTicketCountFromPageIntVal).toEqual(TotalTicketCountFromES);
			});

			it('verify Automation Summary Action Plan page - check for total count for action plan 108', async function(){
				var year_month = await util.getMonthAndYear();
				var TotalTicketCountFromES =  await esQueriesDelivery.getTotalTicketCount(deliveryInsightTestData.eSActionPlanSearchIndex,tenantId,year_month,108);
				dashboardObj.clickDeliveryInsightLink(deliveryInsightTestData.eSAsapDashboardName);
				var totalTicketCountFromPage = await deliveryInsightObj.getDeliveryInsightActionPlanIdCount(deliveryInsightTestData.eSAsapEscalatedTickets);
				var totalTicketCountFromPageIntVal = util.stringToInteger(totalTicketCountFromPage);
				expect(totalTicketCountFromPageIntVal).toEqual(TotalTicketCountFromES);
			});

			it('verify Automation Summary Action Plan page - check for total count for action plan 109', async function(){
				var year_month = await util.getMonthAndYear();
				var TotalTicketCountFromES =  await esQueriesDelivery.getTotalTicketCount(deliveryInsightTestData.eSActionPlanSearchIndex,tenantId,year_month,109);
				dashboardObj.clickDeliveryInsightLink(deliveryInsightTestData.eSAsapDashboardName);
				var totalTicketCountFromPage = await deliveryInsightObj.getDeliveryInsightActionPlanIdCount(deliveryInsightTestData.eSAsapAssistedTickets);
				var totalTicketCountFromPageIntVal = util.stringToInteger(totalTicketCountFromPage);
				expect(totalTicketCountFromPageIntVal).toEqual(TotalTicketCountFromES);
			});

			it('verify Automation Summary Action Plan page - check for total count for action plan 110', async function(){
				var year_month = await util.getMonthAndYear();
				var TotalTicketCountFromES =  await esQueriesDelivery.getTotalTicketCount(deliveryInsightTestData.eSActionPlanSearchIndex,tenantId,year_month,110);
				dashboardObj.clickDeliveryInsightLink(deliveryInsightTestData.eSAsapDashboardName);
				var totalTicketCountFromPage = await deliveryInsightObj.getDeliveryInsightActionPlanIdCount(deliveryInsightTestData.eSAsapOthersTickets);
				var totalTicketCountFromPageIntVal = util.stringToInteger(totalTicketCountFromPage);
				expect(totalTicketCountFromPageIntVal).toEqual(TotalTicketCountFromES);
			});

			it('verify Automation Summary Action Plan page - check for total count for action plan 111', async function(){
				var year_month = await util.getMonthAndYear();
				var TotalTicketCountFromES =  await esQueriesDelivery.getTotalTicketCount(deliveryInsightTestData.eSActionPlanSearchIndex,tenantId,year_month,111);
				await dashboardObj.clickDeliveryInsightLink(deliveryInsightTestData.eSAsapDashboardName);
				var totalTicketCountFromPage = await deliveryInsightObj.getDeliveryInsightActionPlanMultipleTextIdCount(deliveryInsightTestData.eSResolvedVar,1);
				var totalTicketCountFromPageIntVal = util.stringToInteger(totalTicketCountFromPage);
				expect(totalTicketCountFromPageIntVal).toEqual(TotalTicketCountFromES);
			});

			it('verify Automation Summary Action Plan page - check for total count for action plan 112', async function(){
				var year_month = await util.getMonthAndYear();
				var TotalTicketCountFromES =  await esQueriesDelivery.getTotalTicketCount(deliveryInsightTestData.eSActionPlanSearchIndex,tenantId,year_month,112);
				await dashboardObj.clickDeliveryInsightLink(deliveryInsightTestData.eSAsapDashboardName);
				var totalTicketCountFromPage = await deliveryInsightObj.getDeliveryInsightActionPlanMultipleTextIdCount(deliveryInsightTestData.eSResolvedVar,2);
				var totalTicketCountFromPageIntVal = util.stringToInteger(totalTicketCountFromPage);
				expect(totalTicketCountFromPageIntVal).toEqual(TotalTicketCountFromES);
			});

			it('verify Automation Summary Action Plan page - check for total count for action plan 113', async function(){
				var year_month = await util.getMonthAndYear();
				var TotalTicketCountFromES =  await esQueriesDelivery.getTotalTicketCount(deliveryInsightTestData.eSActionPlanSearchIndex,tenantId,year_month,113);
				await dashboardObj.clickDeliveryInsightLink(deliveryInsightTestData.eSAsapDashboardName);
				var totalTicketCountFromPage = await deliveryInsightObj.getDeliveryInsightActionPlanMultipleTextIdCount(deliveryInsightTestData.eSResolvedVar,3);
				var totalTicketCountFromPageIntVal = util.stringToInteger(totalTicketCountFromPage);
				expect(totalTicketCountFromPageIntVal).toEqual(TotalTicketCountFromES);
			});

			it('verify Automation Summary Action Plan page - check for total count for action plan 114', async function(){
				var year_month = await util.getMonthAndYear();
				var TotalTicketCountFromES =  await esQueriesDelivery.getTotalTicketCount(deliveryInsightTestData.eSActionPlanSearchIndex,tenantId,year_month,114);
				await dashboardObj.clickDeliveryInsightLink(deliveryInsightTestData.eSAsapDashboardName);
				var totalTicketCountFromPage = await deliveryInsightObj.getDeliveryInsightActionPlanMultipleTextIdCount(deliveryInsightTestData.eSResolvedVar,4);
				var totalTicketCountFromPageIntVal = util.stringToInteger(totalTicketCountFromPage);
				expect(totalTicketCountFromPageIntVal).toEqual(TotalTicketCountFromES);
			});

			it('verify Automation Summary Action Plan page - check for total count for action plan 115', async function(){
				var year_month = await util.getMonthAndYear();
				var TotalTicketCountFromES =  await esQueriesDelivery.getTotalTicketCount(deliveryInsightTestData.eSActionPlanSearchIndex,tenantId,year_month,115);
				await dashboardObj.clickDeliveryInsightLink(deliveryInsightTestData.eSAsapDashboardName);
				var totalTicketCountFromPage = await deliveryInsightObj.getDeliveryInsightActionPlanMultipleTextIdCount(deliveryInsightTestData.eSResolvedVar,5);
				var totalTicketCountFromPageIntVal = util.stringToInteger(totalTicketCountFromPage);
				expect(totalTicketCountFromPageIntVal).toEqual(TotalTicketCountFromES);
			});

			it('verify Automation Summary Action Plan page - check for total count for action plan 116', async function(){
				var year_month = await util.getMonthAndYear();
				var TotalTicketCountFromES =  await esQueriesDelivery.getTotalTicketCount(deliveryInsightTestData.eSActionPlanSearchIndex,tenantId,year_month,116);
				await dashboardObj.clickDeliveryInsightLink(deliveryInsightTestData.eSAsapDashboardName);
				var totalTicketCountFromPage = await deliveryInsightObj.getDeliveryInsightActionPlanMultipleTextIdCount(deliveryInsightTestData.eSResolvedVar,6);
				var totalTicketCountFromPageIntVal = util.stringToInteger(totalTicketCountFromPage);
				expect(totalTicketCountFromPageIntVal).toEqual(TotalTicketCountFromES);
			});

			it('verify Automation Summary Action Plan page - check for total count for action plan 117', async function(){
				var year_month = await util.getMonthAndYear();
				var TotalTicketCountFromES =  await esQueriesDelivery.getTotalTicketCount(deliveryInsightTestData.eSActionPlanSearchIndex,tenantId,year_month,117);
				await dashboardObj.clickDeliveryInsightLink(deliveryInsightTestData.eSAsapDashboardName);
				var totalTicketCountFromPage = await deliveryInsightObj.getDeliveryInsightActionPlanMultipleTextIdCount(deliveryInsightTestData.eSResolvedVar,7);
				var totalTicketCountFromPageIntVal = util.stringToInteger(totalTicketCountFromPage);
				expect(totalTicketCountFromPageIntVal).toEqual(TotalTicketCountFromES);
			});

			it('verify Automation Summary Action Plan page - check for total count for action plan 118', async function(){
				var year_month = await util.getMonthAndYear();
				var TotalTicketCountFromES =  await esQueriesDelivery.getTotalTicketCount(deliveryInsightTestData.eSActionPlanSearchIndex,tenantId,year_month,118);
				await dashboardObj.clickDeliveryInsightLink(deliveryInsightTestData.eSAsapDashboardName);
				var totalTicketCountFromPage = await deliveryInsightObj.getDeliveryInsightActionPlanMultipleTextIdCount(deliveryInsightTestData.eSResolvedVar,8);
				var totalTicketCountFromPageIntVal = util.stringToInteger(totalTicketCountFromPage);
				expect(totalTicketCountFromPageIntVal).toEqual(TotalTicketCountFromES);
			});

			it('verify Automation Summary Action Plan page - check for total ticket flowing to AE count for widget Opportunity ', async function(){
				var year_month = await util.getMonthAndYear();
				var TotalTicketCountFromES =  await esQueriesDelivery.getAEOpportunityWidgetCount(deliveryInsightTestData.eSActionPlanSearchIndex,tenantId,year_month);
				await dashboardObj.clickDeliveryInsightLink(deliveryInsightTestData.eSAsapDashboardName);
				var totalTicketCountFromPage = await deliveryInsightObj.getDeliveryInsightActionPlanMultipleTextIdCount(deliveryInsightTestData.eSOpportunityVar,1);
				var totalTicketCountFromPageIntVal = util.stringToInteger(totalTicketCountFromPage);
				expect(totalTicketCountFromPageIntVal).toEqual(TotalTicketCountFromES);
			});

			it('verify Automation Summary Action Plan page - check for total ticket not flowing to AE count for widget Opportunity ', async function(){
				var year_month = await util.getMonthAndYear();
				var TotalTicketCountFromES =  await esQueriesDelivery.getNotAEOpportunityWidgetCount(deliveryInsightTestData.eSActionPlanSearchIndex,tenantId,year_month);
				await dashboardObj.clickDeliveryInsightLink(deliveryInsightTestData.eSAsapDashboardName);
				var totalTicketCountFromPage = await deliveryInsightObj.getDeliveryInsightActionPlanMultipleTextIdCount(deliveryInsightTestData.eSOpportunityVar,2);
				var totalTicketCountFromPageIntVal = util.stringToInteger(totalTicketCountFromPage);
				expect(totalTicketCountFromPageIntVal).toEqual(TotalTicketCountFromES);
			});

			it('verify Automation Summary Action Plan page - check for total manual ticket count for widget Opportunity ', async function(){
				var year_month = await util.getMonthAndYear();
				var TotalTicketCountFromES =  await esQueriesDelivery.getManualOpportunityWidgetCount(deliveryInsightTestData.eSActionPlanSearchIndex,tenantId,year_month);
				await dashboardObj.clickDeliveryInsightLink(deliveryInsightTestData.eSAsapDashboardName);
				var totalTicketCountFromPage = await deliveryInsightObj.getDeliveryInsightActionPlanMultipleTextIdCount(deliveryInsightTestData.eSOpportunityVar,3);
				var totalTicketCountFromPageIntVal = util.stringToInteger(totalTicketCountFromPage);
				expect(totalTicketCountFromPageIntVal).toEqual(TotalTicketCountFromES);
			});

			it('verify Automation Summary Action Plan page - check for total ticket flowing to AE count for widget Action Plan Opportunity ', async function(){
		        var year_month = await util.getMonthAndYear();
				var TotalTicketCountFromES =  await esQueriesDelivery.getAEActionPlanOpportunityWidgetCount(deliveryInsightTestData.eSActionPlanSearchIndex,tenantId,year_month);
				await dashboardObj.clickDeliveryInsightLink(deliveryInsightTestData.eSAsapDashboardName);
				var totalTicketCountFromPage = await deliveryInsightObj.getDeliveryInsightActionPlanAddIdCount(deliveryInsightTestData.eSActionPlanIdVar,1);
				var totalTicketCountFromPageIntVal = util.stringToInteger(totalTicketCountFromPage);
				expect(totalTicketCountFromPageIntVal).toEqual(TotalTicketCountFromES);
			});

		    it('verify Automation Summary Action Plan page - check for total ticket not flowing to AE count for widget Action Plan Opportunity ', async function(){
				var year_month = await util.getMonthAndYear();
				var TotalTicketCountFromES =  await esQueriesDelivery.getNotAEActionPlanOpportunityWidgetCount(deliveryInsightTestData.eSActionPlanSearchIndex,tenantId,year_month);
				await dashboardObj.clickDeliveryInsightLink(deliveryInsightTestData.eSAsapDashboardName);
				var totalTicketCountFromPage = await deliveryInsightObj.getDeliveryInsightActionPlanAddIdCount(deliveryInsightTestData.eSActionPlanIdVar,3);
				var totalTicketCountFromPageIntVal = util.stringToInteger(totalTicketCountFromPage);
				expect(totalTicketCountFromPageIntVal).toEqual(TotalTicketCountFromES);
			});

		    it('verify Automation Summary Action Plan page - check for total manual ticket count for widget Action Plan Opportunity ', async function(){
				var year_month = await util.getMonthAndYear();
				var TotalTicketCountFromES =  await esQueriesDelivery.getManualActionPlanOpportunityWidgetCount(deliveryInsightTestData.eSActionPlanSearchIndex,tenantId,year_month);
				await dashboardObj.clickDeliveryInsightLink(deliveryInsightTestData.eSAsapDashboardName);
				var totalTicketCountFromPage = await deliveryInsightObj.getDeliveryInsightActionPlanAddIdCount(deliveryInsightTestData.eSActionPlanIdVar,5);
				var totalTicketCountFromPageIntVal = util.stringToInteger(totalTicketCountFromPage);
				expect(totalTicketCountFromPageIntVal).toEqual(TotalTicketCountFromES);
			});

			it('verify Automation Summary Action Plan page - check for total ticket flowing to AE count for widget Action Zero Opportunity ', async function(){
				var year_month = await util.getMonthAndYear();
				var TotalTicketCountFromES =  await esQueriesDelivery.getActionZeroOpportunityWidgetCount(deliveryInsightTestData.eSActionPlanSearchIndex,tenantId,deliveryInsightTestData.eSAEFlowZeroWidgetHlq,year_month);
				await dashboardObj.clickDeliveryInsightLink(deliveryInsightTestData.eSAsapDashboardName);
				var totalTicketCountFromPage = await deliveryInsightObj.getDeliveryInsightActionPlanMultipleTextIdCount(deliveryInsightTestData.eSActionPlanIdVar,1);
				var totalTicketCountFromPageIntVal = util.stringToInteger(totalTicketCountFromPage);
				expect(totalTicketCountFromPageIntVal).toEqual(TotalTicketCountFromES);
			});

			it('verify Automation Summary Action Plan page - check for total ticket not flowing to AE count for widget Action Zero Opportunity ', async function(){
				var year_month = await util.getMonthAndYear();
				var TotalTicketCountFromES =  await esQueriesDelivery.getActionZeroOpportunityWidgetCount(deliveryInsightTestData.eSActionPlanSearchIndex,tenantId,deliveryInsightTestData.eSAENotFlowZeroWidgetHlq,year_month);
				await dashboardObj.clickDeliveryInsightLink(deliveryInsightTestData.eSAsapDashboardName);
				var totalTicketCountFromPage = await deliveryInsightObj.getDeliveryInsightActionPlanMultipleTextIdCount(deliveryInsightTestData.eSActionPlanIdVar,2);
				var totalTicketCountFromPageIntVal = util.stringToInteger(totalTicketCountFromPage);
				expect(totalTicketCountFromPageIntVal).toEqual(TotalTicketCountFromES);
			});

			it('verify Automation Summary Action Plan page - check for total manual ticket count for widget Action Zero Opportunity ', async function(){
				var year_month = await util.getMonthAndYear();
				var TotalTicketCountFromES =  await esQueriesDelivery.getActionZeroOpportunityWidgetCount(deliveryInsightTestData.eSActionPlanSearchIndex,tenantId,deliveryInsightTestData.eSManualZeroWidgetHlq,year_month);
				await dashboardObj.clickDeliveryInsightLink(deliveryInsightTestData.eSAsapDashboardName);
				var totalTicketCountFromPage = await deliveryInsightObj.getDeliveryInsightActionPlanMultipleTextIdCount(deliveryInsightTestData.eSActionPlanIdVar,3);
				var totalTicketCountFromPageIntVal = util.stringToInteger(totalTicketCountFromPage);
				expect(totalTicketCountFromPageIntVal).toEqual(TotalTicketCountFromES);
			});

			it('verify Automation Summary Action Plan page - check for total ticket flowing to AE count for widget Action Plan 8 ', async function(){
		        var year_month = await util.getMonthAndYear();
				var TotalTicketCountFromES =  await esQueriesDelivery.getActionIdCount(deliveryInsightTestData.eSActionPlanSearchIndex,tenantId,8,deliveryInsightTestData.eSHeaderHlq,year_month);
				await dashboardObj.clickDeliveryInsightLink(deliveryInsightTestData.eSAsapDashboardName);
				var totalTicketCountFromPage = await deliveryInsightObj.getDeliveryInsightActionPlanAddIdCount(deliveryInsightTestData.eSActionPlanIdVar,7);
				var totalTicketCountFromPageIntVal = util.stringToInteger(totalTicketCountFromPage);
				expect(totalTicketCountFromPageIntVal).toEqual(TotalTicketCountFromES);
			});

			it('verify Automation Summary Action Plan page - check for total ticket flowing to AE count for widget Action Plan 4 ', async function(){
		        var year_month = await util.getMonthAndYear();
				var TotalTicketCountFromES =  await esQueriesDelivery.getActionIdCount(deliveryInsightTestData.eSActionPlanSearchIndex,tenantId,4,deliveryInsightTestData.eSHeaderHlq,year_month);
				await dashboardObj.clickDeliveryInsightLink(deliveryInsightTestData.eSAsapDashboardName);
				var totalTicketCountFromPage = await deliveryInsightObj.getDeliveryInsightActionPlanAddIdCount(deliveryInsightTestData.eSActionPlanIdVar,9);
				var totalTicketCountFromPageIntVal = util.stringToInteger(totalTicketCountFromPage);
				expect(totalTicketCountFromPageIntVal).toEqual(TotalTicketCountFromES);
			});

			it('verify Automation Summary Action Plan page - check for total ticket flowing to AE count for widget Action Plan 7 ', async function(){
		        var year_month = await util.getMonthAndYear();
				var TotalTicketCountFromES =  await esQueriesDelivery.getActionIdCount(deliveryInsightTestData.eSActionPlanSearchIndex,tenantId,7,deliveryInsightTestData.eSHeaderHlq,year_month);
				await dashboardObj.clickDeliveryInsightLink(deliveryInsightTestData.eSAsapDashboardName);
				var totalTicketCountFromPage = await deliveryInsightObj.getDeliveryInsightActionPlanAddIdCount(deliveryInsightTestData.eSActionPlanIdVar,11);
				var totalTicketCountFromPageIntVal = util.stringToInteger(totalTicketCountFromPage);
				expect(totalTicketCountFromPageIntVal).toEqual(TotalTicketCountFromES);
			});

			it('verify Automation Summary Action Plan page - check for total ticket flowing to AE count for widget Action Plan 9 ', async function(){
		        var year_month = await util.getMonthAndYear();
				var TotalTicketCountFromES =  await esQueriesDelivery.getActionIdNineCount(deliveryInsightTestData.eSActionPlanSearchIndex,tenantId,deliveryInsightTestData.eSAction9AEHlq,year_month);
				await dashboardObj.clickDeliveryInsightLink(deliveryInsightTestData.eSAsapDashboardName);
				var totalTicketCountFromPage = await deliveryInsightObj.getDeliveryInsightActionPlanAddIdCount(deliveryInsightTestData.eSActionPlanIdVar,13);
				var totalTicketCountFromPageIntVal = util.stringToInteger(totalTicketCountFromPage);
				expect(totalTicketCountFromPageIntVal).toEqual(TotalTicketCountFromES);
			});

			it('verify Automation Summary Action Plan page - check for total ticket flowing to AE count for widget Action Plan 10 ', async function(){
		        var year_month = await util.getMonthAndYear();
				var TotalTicketCountFromES =  await esQueriesDelivery.getActionIdCount(deliveryInsightTestData.eSActionPlanSearchIndex,tenantId,10,deliveryInsightTestData.eSHeaderHlq,year_month);
				await dashboardObj.clickDeliveryInsightLink(deliveryInsightTestData.eSAsapDashboardName);
				var totalTicketCountFromPage = await deliveryInsightObj.getDeliveryInsightActionPlanAddIdCount(deliveryInsightTestData.eSActionPlanIdVar,15);
				var totalTicketCountFromPageIntVal = util.stringToInteger(totalTicketCountFromPage);
				expect(totalTicketCountFromPageIntVal).toEqual(TotalTicketCountFromES);
			});
		}


       /*End -- Automation Summary Action Plan Page Validation*/

        afterAll(async function() {
            launchpadObj.clickOnLogoutAndLogin(browser.params.username, browser.params.password);
        });
    });
