/**
 * Created by : Pushpraj
 * created on : 12/02/2020
 */

"use strict";


var logGenerator = require("../../helpers/logGenerator.js"),
	logger = logGenerator.getApplicationLogger(),
	since = require('jasmine2-custom-message'),
	pervasiveInsightsPage = require('../pageObjects/pervasive_insights.pageObject.js'),
	incident_management = require('../pageObjects/incident_management.pageObject.js'),
	pervasiveInsightsTestData = require('../../testData/cards/pervasiveInsightsTestData.json'),
	incidentManagementTestData = require('../../testData/cards/incidentManagementTestData.json'),
	launchpadPage = require('../pageObjects/launchpad.pageObject.js'),
	launchpadTestData = require('../../testData/cards/launchpadTestData.json'),
	problemManagementPage = require('../pageObjects/problem_management.pageObject.js'),
	dashboardPage = require('../pageObjects/dashboard.pageObject.js'),
	dashboardTestData = require('../../testData/cards/dashboardTestData.json'),
	appUrls = require('../../testData/appUrls.json'),
	frames = require('../../testData/frames.json'),
	serviceMgmtUtil = require('../../helpers/serviceMgmtUtil.js'),
	expectedData = require("../../testData/expected_value/pervasive_insights_expected_values.json"),
	dashboardExpectedData = require("../../testData/expected_value/dashboard_expected_values.json"),
	util = require('../../helpers/util.js'),
	esQueriesPervasive=require('../../elasticSearchTool/esQuery_PervasivePayload.js'),
	tenantId = browser.params.tenantId,
	isEnabledESValidation = browser.params.esValidation;

describe('Pervasive Insights - functionality ', function() {
	var pervasiveInsightsObj, launchpadObj, problemManagementObj, dashboardObj,incidentManagementObj;
	var tabLinkList = [pervasiveInsightsTestData.pervasiveIssueAnalysisTabLink,pervasiveInsightsTestData.topographyTabLink];
	var globalFilterList = [pervasiveInsightsTestData.assignmentQueueFilterName,pervasiveInsightsTestData.serviceLineFilterName,pervasiveInsightsTestData.assignmentGroupFilterName,pervasiveInsightsTestData.applicationsFilterName,pervasiveInsightsTestData.contactTypeFilterName,pervasiveInsightsTestData.opcoFilterName,pervasiveInsightsTestData.autogeneratedFilterName];
	var dateRangeFilterList = [pervasiveInsightsTestData.createdFilterName,pervasiveInsightsTestData.resolvedFilterName];
	var pervasiveIssueAnalysisTabWidgetNameList = [pervasiveInsightsTestData.filterBySection,pervasiveInsightsTestData.serverCountWidgetName,pervasiveInsightsTestData.mttrIncHoldWidgetName, pervasiveInsightsTestData.mttrExcHoldWidgetName, pervasiveInsightsTestData.autoTicketWidgetName, pervasiveInsightsTestData.userTicketWidgetName, pervasiveInsightsTestData.totalTicketCountWidgetName, pervasiveInsightsTestData.capacityNonCapacityWidgetName, pervasiveInsightsTestData.osNonOsDriveWidgetName, pervasiveInsightsTestData.serverRegionWidgetName, pervasiveInsightsTestData.priorityViewWidgetName, pervasiveInsightsTestData.top50ServersWidgetName, pervasiveInsightsTestData.serverFunctionWidgetName, pervasiveInsightsTestData.opcoWidgetName, pervasiveInsightsTestData.top50CategoryWidgetName, pervasiveInsightsTestData.assignmentGroupWidgetName, pervasiveInsightsTestData.DayWiseCategoryTrendWidgetName, pervasiveInsightsTestData.DayWisePriorityTrendWidgetName,pervasiveInsightsTestData.monthWiseTrendWidgetName,pervasiveInsightsTestData.weekWiseTrendWidgetName,pervasiveInsightsTestData.topServersOnIssuesWidgetName, pervasiveInsightsTestData.topIssuesOnServersWidgetName,pervasiveInsightsTestData.incidentDetailsTable];
    var topographyTabWidgetNameList = [pervasiveInsightsTestData.filterBySection,pervasiveInsightsTestData.serverCountWidgetName, pervasiveInsightsTestData.mttrIncHoldWidgetName, pervasiveInsightsTestData.mttrExcHoldWidgetName, pervasiveInsightsTestData.siteIDCountWidgetName, pervasiveInsightsTestData.streetAddrCountWidgetName , pervasiveInsightsTestData.countryViewCountWidgetName, pervasiveInsightsTestData.countryViewWidgetName,pervasiveInsightsTestData.capacityNonCapacityWidgetName,pervasiveInsightsTestData.osNonOsDriveWidgetName,pervasiveInsightsTestData.serverCityViewWidgetName, pervasiveInsightsTestData.buildingIDViewWidgetName, pervasiveInsightsTestData.streetAddrViewWidgetName, pervasiveInsightsTestData.siteIDViewWidgetName, pervasiveInsightsTestData.topCategoryViewWidgetName, pervasiveInsightsTestData.categoryViewForTop10AddrWidgetName,pervasiveInsightsTestData.incidentDetailsTable];		
	var ticketDetailsColumnList = [pervasiveInsightsTestData.numberColumnName, pervasiveInsightsTestData.priorityColumnName, pervasiveInsightsTestData.hostNameColumnName, pervasiveInsightsTestData.serverFunctionColumnName, pervasiveInsightsTestData.serverCapacityColumnName, pervasiveInsightsTestData.serverDriveTypeColumnName, pervasiveInsightsTestData.shortDescColumnName];
	var pervasiveIssueAnalysis_expectedData = expectedData.pervasive_issue_analysis.default_filters.expected_values;
	var topography_expectedData = expectedData.topography.default_filters.expected_values;
	var ticketDetails_expectedData = expectedData.ticket_details;
	var pervasiveInsightsTop5AffectedServers = dashboardExpectedData.pervasive_insights.top_5_affected_servers;
	
	beforeAll(function() {
		pervasiveInsightsObj = new pervasiveInsightsPage();
		launchpadObj = new launchpadPage();
		problemManagementObj = new problemManagementPage();
		incidentManagementObj = new incident_management();
		dashboardObj = new dashboardPage();
	});

	beforeEach(function() {
		launchpadObj.open();
		expect(launchpadObj.getWelcomeMessageTxt()).toEqual(launchpadTestData.welcome);
		pervasiveInsightsObj.open();
		expect(util.getCurrentURL()).toMatch(appUrls.pervasiveInsightPageUrl);
	});

	it("Verify navigation to Pervasive Insights landing page using Common tasks card from Launchpad page", async function(){
		launchpadObj.open();
		await launchpadObj.clickOnTileBasedOnHeaderAndTileName(launchpadTestData.sectionHeader_getStartedHeaderText,launchpadTestData.commonTask_PervasiveCardTitle);
		await expect(util.getCurrentURL()).toMatch(appUrls.pervasiveInsightPageUrl);
		util.switchToDefault();
		util.switchToFrameById(frames.mcmpIframe);
		await expect(util.getHeaderTitleText()).toEqual(pervasiveInsightsTestData.headerTitle);
		util.clickOnHeaderDashboardLink();
		expect(util.getCurrentURL()).toMatch(appUrls.dashboardPageUrl);
	});

	it("Verify navigation to Pervasive Insights landing page using View details link from Dashboard landing page", async function(){
		await launchpadObj.open();
		await launchpadObj.clickOnIntelligentItOprLink();
		await launchpadObj.clickOnDashboardTile(launchpadTestData.learnPage_aiopsDashboardTile);
		await dashboardObj.open();
		expect(await util.getCurrentURL()).toMatch(appUrls.dashboardPageUrl);
        expect(await dashboardObj.getDashboardHeaderTitleText()).toEqual(dashboardTestData.headerTitle);
		await dashboardObj.clickOnViewDetailsLinkBasedOnCard(dashboardTestData.pervasiveInsights);
		util.switchToDefault();
		util.switchToFrameById(frames.mcmpIframe);
		expect(await util.getHeaderTitleText()).toEqual(pervasiveInsightsTestData.headerTitle);
		expect(await util.getCurrentURL()).toMatch(appUrls.pervasiveInsightPageUrl);
	});

	it("Verify info tooltip and tab links", function(){
		serviceMgmtUtil.clickOnLastUpdatedInfoIcon();
		expect(serviceMgmtUtil.getLastUpdatedInfoIconText()).toBe(pervasiveInsightsTestData.headerInfoToolTipText);
		tabLinkList.forEach(function (tabLink) {
			expect(serviceMgmtUtil.getAllTabsLinkText()).toContain(tabLink);
		});
		// Calling again to close the toop tip panel
		serviceMgmtUtil.clickOnLastUpdatedInfoIcon();
	});

	it("Verify Global filters visibility and their default value/tool tip text on Pervasive Issue analysis tab", async function(){
		// Verify if Pervasive Issue Analysis tab is selected by default or not
		expect(serviceMgmtUtil.isTabLinkSelected(pervasiveInsightsTestData.pervasiveIssueAnalysisTabLink)).toBe(true);
		expect(serviceMgmtUtil.isTabLinkSelected(pervasiveInsightsTestData.topographyTabLink)).toBe(false);
		util.switchToFrameById(frames.cssrIFrame);
		util.waitForInvisibilityOfKibanaDataLoader();
		expect(await serviceMgmtUtil.getAllFiltersButtonNameText()).toEqual(jasmine.arrayContaining(globalFilterList));
		expect(await serviceMgmtUtil.getAllFiltersButtonNameText()).toEqual(jasmine.arrayContaining(dateRangeFilterList));
		// Verify default value / tool tip text for each global filter
		expect(serviceMgmtUtil.getGlobalFilterButtonToolTipText(pervasiveInsightsTestData.assignmentQueueFilterName)).toEqual(pervasiveInsightsTestData.noneSelectedTooltipText);
		expect(serviceMgmtUtil.getGlobalFilterButtonToolTipText(pervasiveInsightsTestData.serviceLineFilterName)).toEqual(pervasiveInsightsTestData.noneSelectedTooltipText);
		expect(serviceMgmtUtil.getGlobalFilterButtonToolTipText(pervasiveInsightsTestData.applicationsFilterName)).toEqual(pervasiveInsightsTestData.noneSelectedTooltipText);
		expect(serviceMgmtUtil.getGlobalFilterButtonToolTipText(pervasiveInsightsTestData.assignmentGroupFilterName)).toEqual(pervasiveInsightsTestData.noneSelectedTooltipText);
		expect(serviceMgmtUtil.getGlobalFilterButtonToolTipText(pervasiveInsightsTestData.contactTypeFilterName)).toEqual(pervasiveInsightsTestData.noneSelectedTooltipText);
		expect(serviceMgmtUtil.getGlobalFilterButtonToolTipText(pervasiveInsightsTestData.opcoFilterName)).toEqual(pervasiveInsightsTestData.noneSelectedTooltipText);
		expect(serviceMgmtUtil.getGlobalFilterButtonToolTipText(pervasiveInsightsTestData.autogeneratedFilterName)).toEqual(pervasiveInsightsTestData.noneSelectedTooltipText);
		// Validate the default global filter is applied for "30 days" on Created date-range filter
		expect(serviceMgmtUtil.getDateRangeFilterDateDifference(pervasiveInsightsTestData.createdFilterName)).toEqual(pervasiveInsightsTestData.defaultCreatedFilterDateRangeDiff);
		// Validate each filter is expanded or not
		expect(serviceMgmtUtil.expandGlobalFilterCheck(globalFilterList)).toBe(true);
		// Validate each date-range filter is expanded or not
		expect(serviceMgmtUtil.expandDateFilterCheck(dateRangeFilterList)).toBe(true);
	});

	it("Verify Global filters visibility and their default value/tool tip text on Topography tab", async function(){
		serviceMgmtUtil.clickOnTabLink(pervasiveInsightsTestData.topographyTabLink);
		// Verify if tab is selected, after clicking on it or not
		expect(serviceMgmtUtil.isTabLinkSelected(pervasiveInsightsTestData.pervasiveIssueAnalysisTabLink)).toBe(false);
		expect(serviceMgmtUtil.isTabLinkSelected(pervasiveInsightsTestData.topographyTabLink)).toBe(true);
		util.switchToFrameById(frames.cssrIFrame);
		util.waitForInvisibilityOfKibanaDataLoader();
		expect(await serviceMgmtUtil.getAllFiltersButtonNameText()).toEqual(jasmine.arrayContaining(globalFilterList));
		expect(await serviceMgmtUtil.getAllFiltersButtonNameText()).toEqual(jasmine.arrayContaining(dateRangeFilterList));
		// Verify default value / tool tip text for each global filter
		expect(serviceMgmtUtil.getGlobalFilterButtonToolTipText(pervasiveInsightsTestData.assignmentQueueFilterName)).toEqual(pervasiveInsightsTestData.noneSelectedTooltipText);
		expect(serviceMgmtUtil.getGlobalFilterButtonToolTipText(pervasiveInsightsTestData.serviceLineFilterName)).toEqual(pervasiveInsightsTestData.noneSelectedTooltipText);
		expect(serviceMgmtUtil.getGlobalFilterButtonToolTipText(pervasiveInsightsTestData.applicationsFilterName)).toEqual(pervasiveInsightsTestData.noneSelectedTooltipText);
		expect(serviceMgmtUtil.getGlobalFilterButtonToolTipText(pervasiveInsightsTestData.assignmentGroupFilterName)).toEqual(pervasiveInsightsTestData.noneSelectedTooltipText);
		expect(serviceMgmtUtil.getGlobalFilterButtonToolTipText(pervasiveInsightsTestData.contactTypeFilterName)).toEqual(pervasiveInsightsTestData.noneSelectedTooltipText);
		expect(serviceMgmtUtil.getGlobalFilterButtonToolTipText(pervasiveInsightsTestData.opcoFilterName)).toEqual(pervasiveInsightsTestData.noneSelectedTooltipText);
		expect(serviceMgmtUtil.getGlobalFilterButtonToolTipText(pervasiveInsightsTestData.autogeneratedFilterName)).toEqual(pervasiveInsightsTestData.noneSelectedTooltipText);
		// Validate the default global filter is applied for "30 days" on Created date-range filter
		expect(serviceMgmtUtil.getDateRangeFilterDateDifference(pervasiveInsightsTestData.createdFilterName)).toEqual(pervasiveInsightsTestData.defaultCreatedFilterDateRangeDiff);
		// Validate each filter is expanded or not
		expect(serviceMgmtUtil.expandGlobalFilterCheck(globalFilterList)).toBe(true);
		// Validate each date-range filter is expanded or not
		expect(serviceMgmtUtil.expandDateFilterCheck(dateRangeFilterList)).toBe(true);
	});

	it("Verify default Global date-range labels text is Last 30 days on Pervasive Issue Analysis, Topography tab", async function(){
		serviceMgmtUtil.clickOnTabLink(pervasiveInsightsTestData.pervasiveIssueAnalysisTabLink);
		// Verify if tab is selected, after clicking on it or not
		expect(serviceMgmtUtil.isTabLinkSelected(pervasiveInsightsTestData.pervasiveIssueAnalysisTabLink)).toBe(true);
		util.switchToFrameById(frames.cssrIFrame);
		await util.waitForInvisibilityOfKibanaDataLoader();
		await serviceMgmtUtil.clickOnFilterButtonBasedOnName(pervasiveInsightsTestData.createdFilterName);
		// Set label text as "Showing data for last 30 days"
		var globalDateRangeLabelText = pervasiveInsightsTestData.globalDateRangeLabelText.format(pervasiveInsightsTestData.defaultCreatedFilterDateRangeDiff);
		// Verify by default the tab showing data for 30 days
		await expect(pervasiveInsightsObj.getGlobalDateRangeLabelText()).toEqual(globalDateRangeLabelText);
		util.switchToDefault();
		util.switchToFrameById(frames.mcmpIframe);
		await serviceMgmtUtil.clickOnTabLink(pervasiveInsightsTestData.topographyTabLink);
		// Verify if tab is selected, after clicking on it or not
		await expect(serviceMgmtUtil.isTabLinkSelected(pervasiveInsightsTestData.topographyTabLink)).toBe(true);
		util.switchToFrameById(frames.cssrIFrame);
		await util.waitForInvisibilityOfKibanaDataLoader();
		await serviceMgmtUtil.clickOnFilterButtonBasedOnName(pervasiveInsightsTestData.createdFilterName);
		// Verify by default the tab showing data for 30 days
		await expect(pervasiveInsightsObj.getGlobalDateRangeLabelText()).toEqual(globalDateRangeLabelText);
		util.switchToDefault();
		util.switchToFrameById(frames.mcmpIframe);
	});

	it("Verify Global date-range label selection and reset to default value on Pervasive Issue Analysis, Topography tab", async function(){
		await serviceMgmtUtil.clickOnTabLink(pervasiveInsightsTestData.pervasiveIssueAnalysisTabLink);
		// Verify if tab is selected, after clicking on it or not
		await expect(serviceMgmtUtil.isTabLinkSelected(pervasiveInsightsTestData.pervasiveIssueAnalysisTabLink)).toBe(true);
		util.switchToFrameById(frames.cssrIFrame);
		await util.waitForInvisibilityOfKibanaDataLoader();
		// Set label text as "Showing data for last 210 days"
		var globalDateRangeLabelText = pervasiveInsightsTestData.globalDateRangeLabelText.format(pervasiveInsightsTestData.dateRange210Days);
		//globalDateRangeLabelText = pervasiveInsightsTestData.globalDateRangeLabelText.format(pervasiveInsightsTestData.dateRange210Days);
		await serviceMgmtUtil.clickOnFilterButtonBasedOnName(pervasiveInsightsTestData.createdFilterName);
		await expect(serviceMgmtUtil.verifyDateRangeFilterPanelExpanded(pervasiveInsightsTestData.createdFilterName)).toBe(true);
		await serviceMgmtUtil.selectDateRangeFilterValue(globalDateRangeLabelText);
		await serviceMgmtUtil.clickOnApplyFilterButton();
		//await util.waitForInvisibilityOfKibanaDataLoader();
		// Verify after applying date-range filter, the tab showing data for 210 days
		await serviceMgmtUtil.clickOnFilterButtonBasedOnName(pervasiveInsightsTestData.createdFilterName);
		expect(pervasiveInsightsObj.getGlobalDateRangeLabelText()).toEqual(globalDateRangeLabelText);
		util.switchToDefault();
		util.switchToFrameById(frames.mcmpIframe);
		await serviceMgmtUtil.clickOnTabLink(pervasiveInsightsTestData.topographyTabLink);
		// Verify if tab is selected, after clicking on it or not
		await expect(serviceMgmtUtil.isTabLinkSelected(pervasiveInsightsTestData.topographyTabLink)).toBe(true);
		util.switchToFrameById(frames.cssrIFrame);
		await util.waitForInvisibilityOfKibanaDataLoader();
		// Verify after applying date-range filter, the tab showing data for 210 days
		await serviceMgmtUtil.clickOnFilterButtonBasedOnName(pervasiveInsightsTestData.createdFilterName);
		expect(pervasiveInsightsObj.getGlobalDateRangeLabelText()).toEqual(globalDateRangeLabelText);
	    // Clearing "Created" date-range filter
		await util.clickOnResetFilterLink();
		await util.waitForInvisibilityOfKibanaDataLoader();
		// Set label text as "Showing data for last 30 days"
		globalDateRangeLabelText = pervasiveInsightsTestData.globalDateRangeLabelText.format(pervasiveInsightsTestData.defaultCreatedFilterDateRangeDiff);
		// Verify after clearing dat-range filter, the tab showing data for 30 days
		await serviceMgmtUtil.clickOnFilterButtonBasedOnName(pervasiveInsightsTestData.createdFilterName);
		expect(pervasiveInsightsObj.getGlobalDateRangeLabelText()).toEqual(globalDateRangeLabelText);
		util.switchToDefault();
		util.switchToFrameById(frames.mcmpIframe);
		await serviceMgmtUtil.clickOnTabLink(pervasiveInsightsTestData.pervasiveIssueAnalysisTabLink);
		// Verify if tab is selected, after clicking on it or not
		await expect(serviceMgmtUtil.isTabLinkSelected(pervasiveInsightsTestData.pervasiveIssueAnalysisTabLink)).toBe(true);
		util.switchToFrameById(frames.cssrIFrame);
		await util.waitForInvisibilityOfKibanaDataLoader();
		// Verify after clearing date-range filter, the tab showing data for 30 days
		await serviceMgmtUtil.clickOnFilterButtonBasedOnName(pervasiveInsightsTestData.createdFilterName);
		expect(pervasiveInsightsObj.getGlobalDateRangeLabelText()).toEqual(globalDateRangeLabelText);
	});

	it("Verify Global filters functionality on Pervasive Issue Analysis tab", async function(){
		serviceMgmtUtil.clickOnTabLink(pervasiveInsightsTestData.pervasiveIssueAnalysisTabLink);
		// Verify if tab is selected, after clicking it
        expect(serviceMgmtUtil.isTabLinkSelected(pervasiveInsightsTestData.pervasiveIssueAnalysisTabLink)).toBe(true);
		util.switchToFrameById(frames.cssrIFrame);
		util.waitForInvisibilityOfKibanaDataLoader();
		// Iterate through each multi-select filter, select first value and verify whether value is selected
		var filterValues = await serviceMgmtUtil.selectAndDeselectFilterValue(globalFilterList);
	    await expect(filterValues.appliedFilterValues).toEqual(filterValues.selectedFilterValues);
		//Set date-range filter value
		var rangeFilter = pervasiveInsightsTestData.lastCustomDaysDateRangeText.format(pervasiveInsightsTestData.dateRange210Days);
		// Iterate through each date-range filter, select first value and verify whether value is selected
		var dateFilterValues = await serviceMgmtUtil.selectAndDeselectDateFilterValue(dateRangeFilterList,rangeFilter);
	    await expect(dateFilterValues.appliedFilterValues).toEqual(dateFilterValues.selectedFilterValues);
	});

    it("Verify Global filters functionality on Topography tab", async function(){
		serviceMgmtUtil.clickOnTabLink(pervasiveInsightsTestData.topographyTabLink);
		// Verify if tab is selected, after clicking on it or not
        await expect(serviceMgmtUtil.isTabLinkSelected(pervasiveInsightsTestData.topographyTabLink)).toBe(true);
		util.switchToFrameById(frames.cssrIFrame);
		await util.waitForInvisibilityOfKibanaDataLoader();
		// Iterate through each multi-select filter, select first value and verify whether value is selected
		var filterValues = await serviceMgmtUtil.selectAndDeselectFilterValue(globalFilterList);
	    await expect(filterValues.appliedFilterValues).toEqual(filterValues.selectedFilterValues);

	});

    it("Verify applied Global filter persist across all tabs within Pervasive Insights and won't persist when moved to another report page", async function(){
		serviceMgmtUtil.clickOnTabLink(pervasiveInsightsTestData.pervasiveIssueAnalysisTabLink);
		// Verify if tab is selected, after clicking on it or not
        expect(serviceMgmtUtil.isTabLinkSelected(pervasiveInsightsTestData.pervasiveIssueAnalysisTabLink)).toBe(true);
		util.switchToFrameById(frames.cssrIFrame);
		await util.waitForInvisibilityOfKibanaDataLoader();
		// Apply Contact Type filter with its first value
		await serviceMgmtUtil.clickOnFilterButtonBasedOnName(pervasiveInsightsTestData.contactTypeFilterName);
		expect(serviceMgmtUtil.verifyFilterPanelExpanded(pervasiveInsightsTestData.contactTypeFilterName)).toBe(true);
		var filterValue = await serviceMgmtUtil.selectFirstFilterValueBasedOnName(pervasiveInsightsTestData.contactTypeFilterName);
		await serviceMgmtUtil.clickOnUpdateFilterButton(pervasiveInsightsTestData.contactTypeFilterName);
		await serviceMgmtUtil.clickOnApplyFilterButton();
		//await util.waitForInvisibilityOfKibanaDataLoader();
		// Click on the filter again and get the selected filter value and verify if filter is applied
		await serviceMgmtUtil.clickOnFilterButtonBasedOnName(pervasiveInsightsTestData.contactTypeFilterName);
		var selectedFilterValues = await serviceMgmtUtil.getSelectedItemsFromCheckbox();
		expect(filterValue).toEqual(selectedFilterValues);
		//get the server count from Pervasive issue analysis tab
		var serverCountTab1 = await serviceMgmtUtil.getKabianaBoardCardTextBasedOnName(pervasiveInsightsTestData.serverCountWidgetName);
		util.switchToDefault();
		util.switchToFrameById(frames.mcmpIframe);
		// Navigate to Topography tab 
		await serviceMgmtUtil.clickOnTabLink(pervasiveInsightsTestData.topographyTabLink);
		expect(serviceMgmtUtil.isTabLinkSelected(pervasiveInsightsTestData.topographyTabLink)).toBe(true);
		util.switchToFrameById(frames.cssrIFrame);
		await util.waitForInvisibilityOfKibanaDataLoader();
		// Click on the filter again and get the selected filter value
		await serviceMgmtUtil.clickOnFilterButtonBasedOnName(pervasiveInsightsTestData.contactTypeFilterName);
		selectedFilterValues = await serviceMgmtUtil.getSelectedItemsFromCheckbox();
		//Verify whether filter value is retained in topography tab
		expect(filterValue).toEqual(selectedFilterValues);
		var serverCountTab2 = await serviceMgmtUtil.getKabianaBoardCardTextBasedOnName(pervasiveInsightsTestData.serverCountWidgetName);
		// Verify Server count on Pervasive issue analysis tab equals to Server count on Topography tab
		expect(serverCountTab1).toEqual(serverCountTab2);
	    util.switchToDefault();
		util.switchToFrameById(frames.mcmpIframe);
		// Navigate to Problem Management page
		await launchpadObj.clickOnHamburgerMenu(launchpadTestData.leftNavigationExpanded);
		await launchpadObj.clickOnleftNavigationMenuBasedOnName(launchpadTestData.aIOpsIntelligentITOperationsBtn);
		await launchpadObj.clickLeftNavCardBasedOnName(launchpadTestData.problemManagementCard);
		problemManagementObj.open();
		// Navigate back to Pervasive Insights page
		pervasiveInsightsObj.open();
		expect(serviceMgmtUtil.isTabLinkSelected(pervasiveInsightsTestData.pervasiveIssueAnalysisTabLink)).toBe(true);
		util.switchToFrameById(frames.cssrIFrame);
		await util.waitForInvisibilityOfKibanaDataLoader();
		// Click on the filter again and verify if filters are not retained
		await serviceMgmtUtil.clickOnFilterButtonBasedOnName(pervasiveInsightsTestData.contactTypeFilterName);
		var unSelectedFilterValues = await serviceMgmtUtil.getUnSelectedItemsFromCheckbox();
		expect(unSelectedFilterValues).toEqual(jasmine.arrayContaining(Array.from(filterValue.split(","))));
	});

	it("Validate all widget Names are Present on 'Pervasive Issue Analysis' Tab", async function(){
		await serviceMgmtUtil.clickOnTabLink(pervasiveInsightsTestData.pervasiveIssueAnalysisTabLink);
		// Verify if tab is selected, after clicking on it or not
		await expect(serviceMgmtUtil.isTabLinkSelected(pervasiveInsightsTestData.pervasiveIssueAnalysisTabLink)).toBe(true);
		util.switchToFrameById(frames.cssrIFrame);
		util.waitForInvisibilityOfKibanaDataLoader();
		// Check all widgets on Kibana report are Present
		var widgetsNameFromUI = await serviceMgmtUtil.getAllKibanaReportWidgetsNameText();
		expect(widgetsNameFromUI).toEqual(pervasiveIssueAnalysisTabWidgetNameList);
	});

	it("Validate all widget Names are Present on 'Topography' Tab", async function(){
		await serviceMgmtUtil.clickOnTabLink(pervasiveInsightsTestData.topographyTabLink);
		// Verify if tab is selected, after clicking on it or not
		await expect(serviceMgmtUtil.isTabLinkSelected(pervasiveInsightsTestData.topographyTabLink)).toBe(true);
		util.switchToFrameById(frames.cssrIFrame);
		util.waitForInvisibilityOfKibanaDataLoader();
		// Check all widgets on Kibana report are Present
		var widgetsNameFromUI = await serviceMgmtUtil.getAllKibanaReportWidgetsNameText();
		expect(widgetsNameFromUI).toEqual(topographyTabWidgetNameList);
	});
  
    /*it("Verify Total ticket count from Pervasive Issue Analysis tab with Ticket Details table and downloaded ticket details xlsx", async function(){
		serviceMgmtUtil.clickOnTabLink(pervasiveInsightsTestData.pervasiveIssueAnalysisTabLink);
		// Verify if tab is selected, after clicking on it or not
        expect(serviceMgmtUtil.isTabLinkSelected(pervasiveInsightsTestData.pervasiveIssueAnalysisTabLink)).toBe(true);
		util.switchToFrameById(frames.cssrIFrame);
		await util.waitForInvisibilityOfKibanaDataLoader();
		//Verify total ticket count on Pervasive issue analysis tab with ticket details table row count
		//If Total ticket count >= 10000
		var totalTicketCount = await serviceMgmtUtil.getKabianaBoardCardTextBasedOnName(pervasiveInsightsTestData.totalTicketCountWidgetName);
		// Remove comma (',') from string and convert to integer
		var totalTicketCountInt = util.stringToInteger(totalTicketCount);
		util.switchToDefault();
		util.switchToFrameById(frames.mcmpIframe);
		// Navigate to Ticket details tab
		serviceMgmtUtil.clickOnTabLink(pervasiveInsightsTestData.ticketDetailsTabLink);
		util.switchToFrameById(frames.cssrIFrame);
		await util.waitForInvisibilityOfKibanaDataLoader();
		if(totalTicketCountInt >= 10000){
			// Verify if Ticket details tab table row count equals to Tickets count from Pervasive issue analysis tab
			expect(serviceMgmtUtil.getTicketDetailsTableRowsCount()).toEqual(totalTicketCountInt);
			await serviceMgmtUtil.downloadTicketDetailsXlsx();
			// Verify if the downloaded file exists or not
			expect(util.isTicketDetailsFileExists()).toBe(true);
			var json_data = util.getDataFromXlsxFile();
			// Verify if Tickets count from Json data equals to 10000 [Max number of rows in xlsx file if Total ticket count >= 10000]
			expect(pervasiveInsightsTestData.maxRowsTicketDetailsXlsx).toEqual(util.getTicketCountFromJsonData(json_data));
		}
		 //Verify total ticket count on Pervasive issue analysis tab with ticket details table row count and with downloaded xlsx row count
		 //If Total ticket count < 10000
		util.switchToDefault();
		util.switchToFrameById(frames.mcmpIframe);
		// Navigate to Pervaisve issue analysis tab
		serviceMgmtUtil.clickOnTabLink(pervasiveInsightsTestData.pervasiveIssueAnalysisTabLink);
		util.switchToFrameById(frames.cssrIFrame);
		util.waitForInvisibilityOfKibanaDataLoader();
		// Set Total ticket count below 10K
		await serviceMgmtUtil.setTicketCountBelow10K(pervasiveInsightsTestData.totalTicketCountWidgetName, globalFilterList);
		totalTicketCount = await serviceMgmtUtil.getKabianaBoardCardTextBasedOnName(pervasiveInsightsTestData.totalTicketCountWidgetName);
		// Remove comma (',') from string and convert to integer
		totalTicketCountInt = util.stringToInteger(totalTicketCount);
		util.switchToDefault();
		util.switchToFrameById(frames.mcmpIframe);
		// Navigate to Ticket details tab
        serviceMgmtUtil.clickOnTabLink(pervasiveInsightsTestData.ticketDetailsTabLink);
		util.switchToFrameById(frames.cssrIFrame);
		util.waitForInvisibilityOfKibanaDataLoader();
		// Verify if Ticket details tab table row count equals to Tickets count from Pervasive issue analysis tab
		expect(serviceMgmtUtil.getTicketDetailsTableRowsCount()).toEqual(totalTicketCountInt);
		await serviceMgmtUtil.downloadTicketDetailsXlsx();
		// Verify if the downloaded file exists or not
		expect(util.isTicketDetailsFileExists()).toBe(true);
		var json_data = util.getDataFromXlsxFile();
		// Verify if Tickets count from Pervasive issue analysis tab equals to Tickets count from Json data
		expect(totalTicketCountInt).toEqual(util.getTicketCountFromJsonData(json_data));
	});*/

	/*it("Verify aplied Local filters won't persist across all tabs", async function(){
		await serviceMgmtUtil.clickOnTabLink(pervasiveInsightsTestData.pervasiveIssueAnalysisTabLink);
		// Verify if tab is selected, after clicking on it or not
		await expect(serviceMgmtUtil.isTabLinkSelected(pervasiveInsightsTestData.pervasiveIssueAnalysisTabLink)).toBe(true);
		util.switchToFrameById(frames.cssrIFrame);
		await util.waitForInvisibilityOfKibanaDataLoader();
		// Verify all priority view local filters before click on any one
		var legendsList = await serviceMgmtUtil.getLegendNamesFromLocalFilter(pervasiveInsightsTestData.priorityViewWidgetName);
		var isListEmpty = util.isListEmpty(legendsList);
		expect(isListEmpty).toBe(false);
		if(!isListEmpty){
			legendsList.forEach(function (legendName){
				expect(serviceMgmtUtil.verifySectionFromBoxFilterWidget(pervasiveInsightsTestData.priorityViewWidgetName, legendName)).toBe(true);
			});
			// Click on first priority view filter
			pervasiveInsightsObj.clickOnPriorityViewFilter(legendsList[0]);
			await util.waitForInvisibilityOfKibanaDataLoader();
			// Verify all priority view local filters after click on first one
			expect(serviceMgmtUtil.verifySectionFromBoxFilterWidget(pervasiveInsightsTestData.priorityViewWidgetName,legendsList[0])).toBe(true);
			for(var i=1; i<legendsList.length; i++){
				expect(serviceMgmtUtil.verifySectionFromBoxFilterWidget(pervasiveInsightsTestData.priorityViewWidgetName,legendsList[i])).toBe(false);
			}
			var totalTicketCount = await serviceMgmtUtil.getKabianaBoardCardTextBasedOnName(pervasiveInsightsTestData.totalTicketCountWidgetName);
			var totalTicketCountIntBefore = util.stringToInteger(totalTicketCount);
			// Verify if the Total ticket count from widget equals to Tooltip text ticket count from selected priority view filter
			expect(serviceMgmtUtil.getCountFromBoxFilterSections(pervasiveInsightsTestData.priorityViewWidgetName, legendsList[0])).toEqual(totalTicketCountIntBefore);
			var serverCountFromPervasiveIssueAnalysisTab = await serviceMgmtUtil.getKabianaBoardCardTextBasedOnName(pervasiveInsightsTestData.serverCountWidgetName);
			var serverCountFromPervasiveIssueAnalysisTabInt = util.stringToInteger(serverCountFromPervasiveIssueAnalysisTab);
			// Navigate to Topography tab
			util.switchToDefault();
			util.switchToFrameById(frames.mcmpIframe);
			await serviceMgmtUtil.clickOnTabLink(pervasiveInsightsTestData.topographyTabLink);
			// Verify if tab is selected, after clicking on it or not
			await expect(serviceMgmtUtil.isTabLinkSelected(pervasiveInsightsTestData.topographyTabLink)).toBe(true);
			util.switchToFrameById(frames.cssrIFrame);
			await util.waitForInvisibilityOfKibanaDataLoader();
			var serverCountFromTopographyTab = await serviceMgmtUtil.getKabianaBoardCardTextBasedOnName(pervasiveInsightsTestData.serverCountWidgetName);
			var serverCountFromTopographyTabInt = util.stringToInteger(serverCountFromTopographyTab);
			// Verify if Server count on Pervasive issue analysis tab not equals to Server count on Topography tab
			expect(serverCountFromPervasiveIssueAnalysisTabInt).toBeLessThan(serverCountFromTopographyTabInt);
			// Navigate to Ticket details tab
			util.switchToDefault();
			util.switchToFrameById(frames.mcmpIframe);
			await serviceMgmtUtil.clickOnTabLink(pervasiveInsightsTestData.ticketDetailsTabLink);
			// Verify if tab is selected, after clicking on it or not
			await expect(serviceMgmtUtil.isTabLinkSelected(pervasiveInsightsTestData.ticketDetailsTabLink)).toBe(true);
			util.switchToFrameById(frames.cssrIFrame);
			await util.waitForInvisibilityOfKibanaDataLoader();
			// Verify if Ticket details tab table row count not equals to Tickets count from Pervasive issue analysis tab
			expect(totalTicketCountIntBefore).toBeLessThan(serviceMgmtUtil.getTicketDetailsTableRowsCount());
			// Navigate to Pervasive issue analysis tab
			util.switchToDefault();
			util.switchToFrameById(frames.mcmpIframe);
			await serviceMgmtUtil.clickOnTabLink(pervasiveInsightsTestData.pervasiveIssueAnalysisTabLink);
			// Verify if tab is selected, after clicking on it or not
			await expect(serviceMgmtUtil.isTabLinkSelected(pervasiveInsightsTestData.pervasiveIssueAnalysisTabLink)).toBe(true);
			util.switchToFrameById(frames.cssrIFrame);
			await util.waitForInvisibilityOfKibanaDataLoader();
			// Verify all priority view local filters
			legendsList.forEach(function (legendName){
				expect(serviceMgmtUtil.verifySectionFromBoxFilterWidget(pervasiveInsightsTestData.priorityViewWidgetName,legendName)).toBe(true);
			});
			totalTicketCount = await serviceMgmtUtil.getKabianaBoardCardTextBasedOnName(pervasiveInsightsTestData.totalTicketCountWidgetName);
			var totalTicketCountIntAfter = util.stringToInteger(totalTicketCount);
			// Verify Total ticket count after applying local filters and navigate back to same tab
			expect(totalTicketCountIntBefore).toBeLessThan(totalTicketCountIntAfter);
		}
	});

	it("Verify Box local filters on Pervasive Issue Analysis tab", async function(){
		var isPresent = true;
		await serviceMgmtUtil.clickOnTabLink(pervasiveInsightsTestData.pervasiveIssueAnalysisTabLink);
		// Verify if tab is selected, after clicking on it or not
		await expect(serviceMgmtUtil.isTabLinkSelected(pervasiveInsightsTestData.pervasiveIssueAnalysisTabLink)).toBe(true);
		util.switchToFrameById(frames.cssrIFrame);
		await util.waitForInvisibilityOfKibanaDataLoader();
		// Verify box local filters [Server count, Opco, Top 50 category, Assignment group] ticket count with Total ticket count widget
		isPresent = await serviceMgmtUtil.clickOnFirstBoxLocalFilter(pervasiveInsightsTestData.serverFunctionWidgetName);
		util.waitForInvisibilityOfKibanaDataLoader();
		if(isPresent){
			var ticketCountFromServerCountLocalFilterTooltip = await serviceMgmtUtil.getTicketCountFromBoxLocalFilterTooltipText(pervasiveInsightsTestData.serverFunctionWidgetName);
			var totalTicketCount = await serviceMgmtUtil.getKabianaBoardCardTextBasedOnName(pervasiveInsightsTestData.totalTicketCountWidgetName);
			expect(ticketCountFromServerCountLocalFilterTooltip).toEqual(util.stringToInteger(totalTicketCount));
		}
		isPresent = await serviceMgmtUtil.clickOnFirstBoxLocalFilter(pervasiveInsightsTestData.opcoWidgetName);
		util.waitForInvisibilityOfKibanaDataLoader();
		if(isPresent){
			var ticketCountFromOpcoLocalFilterTooltip = await serviceMgmtUtil.getTicketCountFromBoxLocalFilterTooltipText(pervasiveInsightsTestData.opcoWidgetName);
			totalTicketCount = await serviceMgmtUtil.getKabianaBoardCardTextBasedOnName(pervasiveInsightsTestData.totalTicketCountWidgetName);
			expect(ticketCountFromOpcoLocalFilterTooltip).toEqual(util.stringToInteger(totalTicketCount));
		}
		isPresent = await serviceMgmtUtil.clickOnFirstBoxLocalFilter(pervasiveInsightsTestData.top50CategoryWidgetName);
		util.waitForInvisibilityOfKibanaDataLoader();
		if(isPresent){
			var ticketCountFromTop50CategoryLocalFilterTooltip = await serviceMgmtUtil.getTicketCountFromBoxLocalFilterTooltipText(pervasiveInsightsTestData.top50CategoryWidgetName);
			totalTicketCount = await serviceMgmtUtil.getKabianaBoardCardTextBasedOnName(pervasiveInsightsTestData.totalTicketCountWidgetName);
			expect(ticketCountFromTop50CategoryLocalFilterTooltip).toEqual(util.stringToInteger(totalTicketCount));
		}
		isPresent = await serviceMgmtUtil.clickOnFirstBoxLocalFilter(pervasiveInsightsTestData.assignmentGroupWidgetName);
		util.waitForInvisibilityOfKibanaDataLoader();
		if(isPresent){
			var ticketCountFromAssignmentGrpLocalFilterTooltip = await serviceMgmtUtil.getTicketCountFromBoxLocalFilterTooltipText(pervasiveInsightsTestData.assignmentGroupWidgetName);
			totalTicketCount = await serviceMgmtUtil.getKabianaBoardCardTextBasedOnName(pervasiveInsightsTestData.totalTicketCountWidgetName);
			expect(ticketCountFromAssignmentGrpLocalFilterTooltip).toEqual(util.stringToInteger(totalTicketCount));
		}
	});

	it("Verify Box local filters on Topography tab", async function(){
		var isPresent = true;
		await serviceMgmtUtil.clickOnTabLink(pervasiveInsightsTestData.topographyTabLink);
		// Verify if tab is selected, after clicking on it or not
		await expect(serviceMgmtUtil.isTabLinkSelected(pervasiveInsightsTestData.topographyTabLink)).toBe(true);
		util.switchToFrameById(frames.cssrIFrame);
		await util.waitForInvisibilityOfKibanaDataLoader();
		var totalTicketCountBeforeLocalFilter = await serviceMgmtUtil.getKabianaBoardCardTextBasedOnName(pervasiveInsightsTestData.streetAddrCountWidgetName);
		// Verify box local filter [Street Address View] ticket count with Total ticket count widget
		isPresent = await serviceMgmtUtil.clickOnFirstBoxLocalFilter(pervasiveInsightsTestData.streetAddrViewWidgetName);
		await util.waitForInvisibilityOfKibanaDataLoader();
		if(isPresent){
			await serviceMgmtUtil.getTicketCountFromBoxLocalFilterTooltipText(pervasiveInsightsTestData.streetAddrViewWidgetName);
			var totalTicketCountAfterLocalFilter = await serviceMgmtUtil.getKabianaBoardCardTextBasedOnName(pervasiveInsightsTestData.streetAddrCountWidgetName);
			expect(totalTicketCountAfterLocalFilter).toBeLessThan(totalTicketCountBeforeLocalFilter);
		}
	});

	it("Verify reset global filters functionality", async function(){
		serviceMgmtUtil.clickOnTabLink(pervasiveInsightsTestData.pervasiveIssueAnalysisTabLink);
		// Verify if tab is selected, after clicking on it or not
		expect(serviceMgmtUtil.isTabLinkSelected(pervasiveInsightsTestData.pervasiveIssueAnalysisTabLink)).toBe(true);
		util.switchToFrameById(frames.cssrIFrame);
		await util.waitForInvisibilityOfKibanaDataLoader();
		var totalTicketCountBefore = await serviceMgmtUtil.getKabianaBoardCardTextBasedOnName(pervasiveInsightsTestData.totalTicketCountWidgetName);
		// Remove comma (',') from string and convert to integer
		var totalTicketCountBeforeInt = util.stringToInteger(totalTicketCountBefore);
		// Validate the default global filter is applied for "Last 30 days" on Created date-range filter
		expect(serviceMgmtUtil.getDateRangeFilterDateDifference(pervasiveInsightsTestData.createdFilterName)).toEqual(pervasiveInsightsTestData.defaultCreatedFilterDateRangeDiff);
		// Verify default tooltip text for global filter Assignment Queue
		expect(serviceMgmtUtil.getGlobalFilterButtonToolTipText(pervasiveInsightsTestData.assignmentQueueFilterName)).toEqual(pervasiveInsightsTestData.noneSelectedTooltipText);
		// Apply Assignment Queue filter with its first value
		serviceMgmtUtil.clickOnFilterButtonBasedOnName(pervasiveInsightsTestData.assignmentQueueFilterName);
		expect(serviceMgmtUtil.verifyFilterPanelExpanded(pervasiveInsightsTestData.assignmentQueueFilterName)).toBe(true);
		var filterValue = await serviceMgmtUtil.selectFirstFilterValueBasedOnName(pervasiveInsightsTestData.assignmentQueueFilterName);
		await serviceMgmtUtil.clickOnUpdateFilterButton(pervasiveInsightsTestData.assignmentQueueFilterName);
		await serviceMgmtUtil.clickOnApplyFilterButton();
		await util.waitForInvisibilityOfKibanaDataLoader();
		// Verify tooltip text with applied filter value
		expect(serviceMgmtUtil.getGlobalFilterButtonToolTipText(pervasiveInsightsTestData.assignmentQueueFilterName)).toEqual(filterValue);
		// Apply created date-range filter with "Last 7 days" value
		var last7DaysText = pervasiveInsightsTestData.lastCustomDaysDateRangeText.format(pervasiveInsightsTestData.dateRange7Days);
		await serviceMgmtUtil.clickOnDateRangeFilterButton(pervasiveInsightsTestData.createdFilterName);
		await expect(serviceMgmtUtil.verifyDateRangeFilterPanelExpanded(pervasiveInsightsTestData.createdFilterName)).toBe(true);
		await serviceMgmtUtil.selectDateRangeFilterValue(last7DaysText);
		await serviceMgmtUtil.clickOnApplyFilterButton();
		await util.waitForInvisibilityOfKibanaDataLoader();
		// Verify tooltip text with applied filter value
		await expect(serviceMgmtUtil.getDaysFromDateRangeFilterToolTip(pervasiveInsightsTestData.createdFilterName)).toEqual(pervasiveInsightsTestData.dateRange7Days);
		var totalTicketCountAfter = await serviceMgmtUtil.getKabianaBoardCardTextBasedOnName(pervasiveInsightsTestData.totalTicketCountWidgetName);
		// Remove comma (',') from string and convert to integer
		var totalTicketCountAfterInt = util.stringToInteger(totalTicketCountAfter);
		expect(totalTicketCountAfterInt).toBeLessThan(totalTicketCountBeforeInt);
		await util.clickOnResetFilterLink();
		await util.waitForInvisibilityOfKibanaDataLoader();
		// Verify tooltip text after reset filters
		expect(await serviceMgmtUtil.getGlobalFilterButtonToolTipText(pervasiveInsightsTestData.assignmentQueueFilterName)).toEqual(pervasiveInsightsTestData.noneSelectedTooltipText);
		// Verify date diff for created date range filter after reset filter
		expect(await serviceMgmtUtil.getDateRangeFilterDateDifference(pervasiveInsightsTestData.createdFilterName)).toEqual(pervasiveInsightsTestData.defaultCreatedFilterDateRangeDiff);
		totalTicketCountAfter = await serviceMgmtUtil.getKabianaBoardCardTextBasedOnName(pervasiveInsightsTestData.totalTicketCountWidgetName);
		// Remove comma (',') from string and convert to integer
		totalTicketCountAfterInt = util.stringToInteger(totalTicketCountAfter);
		expect(totalTicketCountBeforeInt).toEqual(totalTicketCountAfterInt);
	});

	it("Total ticket count and priority total in priority view widget should match", async function() {
		serviceMgmtUtil.clickOnTabLink(pervasiveInsightsTestData.pervasiveIssueAnalysisTabLink);
		// Verify if tab is selected, after clicking on it or not
        expect(serviceMgmtUtil.isTabLinkSelected(pervasiveInsightsTestData.pervasiveIssueAnalysisTabLink)).toBe(true);
		util.switchToFrameById(frames.cssrIFrame);
		util.waitForInvisibilityOfKibanaDataLoader();
		var totalTicketCount = await serviceMgmtUtil.getKabianaBoardCardTextBasedOnName(pervasiveInsightsTestData.totalTicketCountWidgetName);
		// Remove comma (',') from string and convert to integer
		var totalTicketCountInt = util.stringToInteger(totalTicketCount);
		//Getting total priority value
		var totalpriority = await serviceMgmtUtil.getTreemapHoverTooltipValue(pervasiveInsightsTestData.priorityViewWidgetName);
		expect(totalpriority).toEqual(totalTicketCountInt);
	}); */

	it("Total ticket comparsion with other widgets", async function() {
		// Compare total ticket widget with Capacity vs Non Capacity, OS vs Non OS Drive, Server Region & Auto Ticket + Manual Ticket widget
		serviceMgmtUtil.clickOnTabLink(pervasiveInsightsTestData.pervasiveIssueAnalysisTabLink);
		// Verify if tab is selected, after clicking on it or not
        expect(serviceMgmtUtil.isTabLinkSelected(pervasiveInsightsTestData.pervasiveIssueAnalysisTabLink)).toBe(true);
		util.switchToFrameById(frames.cssrIFrame);
		await util.waitForInvisibilityOfKibanaDataLoader();
		util.waitForAngular();
		var totalTicketCount = await serviceMgmtUtil.getKabianaBoardCardTextBasedOnName(pervasiveInsightsTestData.totalTicketCountWidgetName);
		// Remove comma (',') from string and convert to integer
		var totalTicketCountInt = util.stringToInteger(totalTicketCount);
		var totalVal1 = await serviceMgmtUtil.getTooltipCountFromDonutChart(pervasiveInsightsTestData.capacityNonCapacityWidgetName);
		since("Total ticket widget vs Capacity Widget validation").expect(totalTicketCountInt).toEqual(totalVal1);
		var totalVal2 = await serviceMgmtUtil.getTooltipCountFromDonutChart(pervasiveInsightsTestData.osNonOsDriveWidgetName);
		since("Total ticket widget vs OS Widget validation").expect(totalTicketCountInt).toEqual(totalVal2);
		var totalVal3 = await serviceMgmtUtil.getTooltipCountFromDonutChart(pervasiveInsightsTestData.serverRegionWidgetName);
		since("Total ticket widget vs server region Widget validation").expect(totalTicketCountInt).toEqual(totalVal3);
		const autoTicketCount = await serviceMgmtUtil.getKabianaBoardCardTextBasedOnName(pervasiveInsightsTestData.autoTicketWidgetName);
		// Remove comma (',') from string and convert to integer
		var autoTicketCountInt = util.stringToInteger(autoTicketCount);
		const userTicketCount = await serviceMgmtUtil.getKabianaBoardCardTextBasedOnName(pervasiveInsightsTestData.userTicketWidgetName);
		// Remove comma (',') from string and convert to integer
		var userTicketCountInt = util.stringToInteger(userTicketCount);
		const totalCount = autoTicketCountInt + userTicketCountInt;
		since("Total ticket widget vs Auto+user Manual Widget validation").expect(totalTicketCountInt).toEqual(totalCount);

	});

	/*it("Pervasive ticket count should match Incident count for last 30 days", async function(){
		logger.info("-------------Pervasive ticket count vs Incident count----------------")
		serviceMgmtUtil.clickOnTabLink(pervasiveInsightsTestData.pervasiveIssueAnalysisTabLink);
		// Verify if tab is selected, after clicking on it or not
		expect(serviceMgmtUtil.isTabLinkSelected(pervasiveInsightsTestData.pervasiveIssueAnalysisTabLink)).toBe(true);
		util.switchToFrameById(frames.cssrIFrame);
		await util.waitForInvisibilityOfKibanaDataLoader();
		// Validate the default global filter is applied for "Last 30 days" on Created date-range filter
		expect(serviceMgmtUtil.getDateRangeFilterDateDifference(pervasiveInsightsTestData.createdFilterName)).toEqual(pervasiveInsightsTestData.defaultCreatedFilterDateRangeDiff);
		var totalTicketCount = await serviceMgmtUtil.getKabianaBoardCardTextBasedOnName(pervasiveInsightsTestData.totalTicketCountWidgetName);
		// Remove comma (',') from string and convert to integer
		var totalTicketCountInt = util.stringToInteger(totalTicketCount);
		//Navigate to Incident Managememt page
		launchpadObj.clickOnHamburgerMenu(launchpadTestData.leftNavigationExpanded);
		launchpadObj.clickOnleftNavigationMenuBasedOnName(launchpadTestData.aIOpsIntelligentITOperationsBtn);
		launchpadObj.clickLeftNavCardBasedOnName(launchpadTestData.incidentManagementCard);
		incidentManagementObj.open();
        expect(util.getCurrentURL()).toMatch(appUrls.incidentManagementPageUrl);
		serviceMgmtUtil.clickOnTabLink(incidentManagementTestData.incidentDashboardTabLink);
		// Verify if incident tab is selected, after clicking on it or not
        expect(serviceMgmtUtil.isTabLinkSelected(incidentManagementTestData.incidentDashboardTabLink)).toBe(true);
		util.switchToFrameById(frames.cssrIFrame);
		await util.waitForInvisibilityOfKibanaDataLoader();
		// Apply created date-range filter with "Last 30 days" value
		await serviceMgmtUtil.clickOnDateRangeFilterButton(incidentManagementTestData.createdFilterName);
		await expect(serviceMgmtUtil.verifyDateRangeFilterPanelExpanded(incidentManagementTestData.createdFilterName)).toBe(true);
		await serviceMgmtUtil.selectDateRangeFilterValue(incidentManagementTestData.dateRangeFilterLast30Days);
		await serviceMgmtUtil.clickOnApplyFilterButton();
		await util.waitForInvisibilityOfKibanaDataLoader();
		// Verify tooltip text with applied filter value
		await expect(serviceMgmtUtil.getDaysFromDateRangeFilterToolTip(incidentManagementTestData.createdFilterName)).toEqual(incidentManagementTestData.dateRangeFilter30DaysDiff);
		// Verify the incoming vol after the "Last 30 days" filter is applied
		var incomingVolFromIncidentDashboard = await serviceMgmtUtil.getKabianaBoardCardTextBasedOnName(incidentManagementTestData.incomingVolWidgetName);
		var incomingVolInt = util.stringToInteger(incomingVolFromIncidentDashboard);
		//Compare ticket count in pervasive with incident ticket count for last 30 days
		expect(totalTicketCountInt).toEqual(incomingVolInt)
	});*/

	it("Elastic validation for Number cards for ticket count on Pervasive dashboard tab", async function(){
		logger.info("------Number cards : ES Data validation------");
		// Verify if tab is selected, after clicking on it or not
		expect(serviceMgmtUtil.isTabLinkSelected(pervasiveInsightsTestData.pervasiveIssueAnalysisTabLink)).toBe(true);
		util.switchToFrameById(frames.cssrIFrame);
		await util.waitForInvisibilityOfKibanaDataLoader();
		var totalTicketCountFromPervasiveDashboard = util.stringToInteger(await serviceMgmtUtil.getKabianaBoardCardTextBasedOnName(pervasiveInsightsTestData.totalTicketCountWidgetName));
		var serverCountFromPervasiveDashboard = util.stringToInteger(await serviceMgmtUtil.getKabianaBoardCardTextBasedOnName(pervasiveInsightsTestData.serverCountWidgetName));
		var mttrInclCountFromPervasiveDashboard = await serviceMgmtUtil.getKabianaBoardCardTextBasedOnName(pervasiveInsightsTestData.mttrIncHoldWidgetName);
		var mttrExclCountFromPervasiveDashboard = await serviceMgmtUtil.getKabianaBoardCardTextBasedOnName(pervasiveInsightsTestData.mttrExcHoldWidgetName);
		var autoTicketCountFromPervasiveDashboard = util.stringToInteger(await serviceMgmtUtil.getKabianaBoardCardTextBasedOnName(pervasiveInsightsTestData.autoTicketWidgetName));
		var userTicketCountFromPervasiveDashboard = util.stringToInteger(await serviceMgmtUtil.getKabianaBoardCardTextBasedOnName(pervasiveInsightsTestData.userTicketWidgetName));

		if(isEnabledESValidation) {
			var totalTktCntFromES = await esQueriesPervasive.totalTickets(pervasiveInsightsTestData.esPervasiveIndex,tenantId);
			var serverCntFromES = await esQueriesPervasive.serverCount(pervasiveInsightsTestData.esPervasiveIndex,tenantId);
			var mttrInclCntFromES = await esQueriesPervasive.mttrInclCount(pervasiveInsightsTestData.esPervasiveIndex,tenantId);
			var mttrExclCntFromES = await esQueriesPervasive.mttrExclCount(pervasiveInsightsTestData.esPervasiveIndex,tenantId);
			var autoTicketCntFromES = await esQueriesPervasive.autoTicketCount(pervasiveInsightsTestData.esPervasiveIndex,tenantId);
			var userTicketCntFromES = await esQueriesPervasive.userTicketCount(pervasiveInsightsTestData.esPervasiveIndex,tenantId);
			expect(totalTicketCountFromPervasiveDashboard).toEqual(totalTktCntFromES);
			expect(serverCountFromPervasiveDashboard).toEqual(serverCntFromES);
			expect(mttrInclCountFromPervasiveDashboard).toEqual(mttrInclCntFromES);
			expect(mttrExclCountFromPervasiveDashboard).toEqual(mttrExclCntFromES);
			expect(autoTicketCountFromPervasiveDashboard).toEqual(autoTicketCntFromES);
			expect(userTicketCountFromPervasiveDashboard).toEqual(userTicketCntFromES);
		}
		// Navigate to Topography tab
		util.switchToDefault();
		util.switchToFrameById(frames.mcmpIframe);
		await serviceMgmtUtil.clickOnTabLink(pervasiveInsightsTestData.topographyTabLink);
		// Verify if tab is selected, after clicking on it or not
		await expect(serviceMgmtUtil.isTabLinkSelected(pervasiveInsightsTestData.topographyTabLink)).toBe(true);
		util.switchToFrameById(frames.cssrIFrame);
		await util.waitForInvisibilityOfKibanaDataLoader();
		var serverCountFromTopography = util.stringToInteger(await serviceMgmtUtil.getKabianaBoardCardTextBasedOnName(pervasiveInsightsTestData.serverCountWidgetName));
		var mttrInclCounFromTopography = await serviceMgmtUtil.getKabianaBoardCardTextBasedOnName(pervasiveInsightsTestData.mttrIncHoldWidgetName);
		var mttrExclCountFromTopography = await serviceMgmtUtil.getKabianaBoardCardTextBasedOnName(pervasiveInsightsTestData.mttrExcHoldWidgetName);
		expect(serverCountFromPervasiveDashboard).toEqual(serverCountFromTopography);
		expect(mttrInclCountFromPervasiveDashboard).toEqual(mttrInclCounFromTopography);
		expect(mttrExclCountFromPervasiveDashboard).toEqual(mttrExclCountFromTopography);
	});

	if(isEnabledESValidation) {
		/*it("Elastic validation for 'Top 50 servers' on Pervasive dashboard tab", async function(){
			logger.info("------ Top 50 servers on Pervasive dashboard tab : ES Data validation------");
			let flag = true;
			// Verify if tab is selected, after clicking on it or not
			expect(serviceMgmtUtil.isTabLinkSelected(pervasiveInsightsTestData.pervasiveIssueAnalysisTabLink)).toBe(true);
			util.switchToFrameById(frames.cssrIFrame);
			await util.waitForInvisibilityOfKibanaDataLoader();
			util.waitForAngular();
			var tagListUI = await serviceMgmtUtil.getKabianaBoardCardCloudTagListBasedOnName(pervasiveInsightsTestData.top50ServersWidgetName);
			var cloudtagListFromES = await esQueriesPervasive.Top50Servers(pervasiveInsightsTestData.esPervasiveIndex,tenantId);
			expect(true).toEqual(pervasiveInsightsObj.getCloudTagListStatus(tagListUI,cloudtagListFromES));
		});

		it("Elastic validation for 'Server function' on Pervasive dashboard tab", async function(){
			logger.info("------ server function on Pervasive dashboard tab : ES Data validation------");
			// Verify if tab is selected, after clicking on it or not
			expect(serviceMgmtUtil.isTabLinkSelected(pervasiveInsightsTestData.pervasiveIssueAnalysisTabLink)).toBe(true);
			util.switchToFrameById(frames.cssrIFrame);
			await util.waitForInvisibilityOfKibanaDataLoader();
			util.waitForAngular();
			var serverFunObjFromES = await esQueriesPervasive.serverFunction(pervasiveInsightsTestData.esPervasiveIndex,tenantId);
			expect(await serviceMgmtUtil.verifyValuesFromJSONAndUIForBoxFilters(pervasiveInsightsTestData.serverFunctionWidgetDataTitleName,serverFunObjFromES)).toBe(true);
		});

		it("Elastic validation for 'OpCo' on Pervasive dashboard tab", async function(){
			logger.info("------ OpCo on Pervasive dashboard tab : ES Data validation------");
			// Verify if tab is selected, after clicking on it or not
			expect(serviceMgmtUtil.isTabLinkSelected(pervasiveInsightsTestData.pervasiveIssueAnalysisTabLink)).toBe(true);
			util.switchToFrameById(frames.cssrIFrame);
			await util.waitForInvisibilityOfKibanaDataLoader();
			util.waitForAngular();
			var opcoObjFromES = await esQueriesPervasive.OpCo(pervasiveInsightsTestData.esPervasiveIndex,tenantId);
			expect(await serviceMgmtUtil.verifyValuesFromJSONAndUIForBoxFilters(pervasiveInsightsTestData.opcoWidgetNameDataTitleName,opcoObjFromES)).toBe(true);
		});

		it("Elastic validation for 'Top 50 category' on Pervasive dashboard tab", async function(){
			logger.info("------ Top 50 category on Pervasive dashboard tab :ES Data validation------");
			// Verify if tab is selected, after clicking on it or not
			expect(serviceMgmtUtil.isTabLinkSelected(pervasiveInsightsTestData.pervasiveIssueAnalysisTabLink)).toBe(true);
			util.switchToFrameById(frames.cssrIFrame);
			await util.waitForInvisibilityOfKibanaDataLoader();
			util.waitForAngular();
			var top50CatObjFromES = await esQueriesPervasive.top50Category(pervasiveInsightsTestData.esPervasiveIndex,tenantId);
			expect(await serviceMgmtUtil.verifyValuesFromJSONAndUIForBoxFilters(pervasiveInsightsTestData.top50CategoryWidgetNameDataTitleName,top50CatObjFromES)).toBe(true);
		});

		it("Elastic validation for 'Assignment Group' on Pervasive dashboard tab", async function(){
			logger.info("------ Assignment Group on Pervasive dashboard tab : ES Data validation------");
			// Verify if tab is selected, after clicking on it or not
			expect(serviceMgmtUtil.isTabLinkSelected(pervasiveInsightsTestData.pervasiveIssueAnalysisTabLink)).toBe(true);
			util.switchToFrameById(frames.cssrIFrame);
			await util.waitForInvisibilityOfKibanaDataLoader();
			util.waitForAngular();
			var assgnGrpObjFromES = await esQueriesPervasive.assignmentGroup(pervasiveInsightsTestData.esPervasiveIndex,tenantId);
			expect(await serviceMgmtUtil.verifyValuesFromJSONAndUIForBoxFilters(pervasiveInsightsTestData.assignmentGroupWidgetNameDataTitleName,assgnGrpObjFromES)).toBe(true);
		});*/

		it("Elastic validation for 'Month Wise Trend' Vertical Bar chart widget on Pervasive Issue Analysis tab", async function(){
			logger.info("------Month Wise Trend :ES Data validation------");
			await serviceMgmtUtil.clickOnTabLink(pervasiveInsightsTestData.pervasiveIssueAnalysisTabLink);
			// Verify if tab is selected, after clicking on it or not
			await expect(serviceMgmtUtil.isTabLinkSelected(pervasiveInsightsTestData.pervasiveIssueAnalysisTabLink)).toBe(true);
			util.switchToFrameById(frames.cssrIFrame);
			await util.waitForInvisibilityOfKibanaDataLoader();
			var mnthWiseObjFromES = await esQueriesPervasive.monthWiseTrend(pervasiveInsightsTestData.esPervasiveIndex,tenantId);
			var xAxisLabels = util.getJSONObjectKeys(mnthWiseObjFromES);
			var countValues = util.getJSONObjectValues(mnthWiseObjFromES);
			for(var i=0; i<xAxisLabels.length; i++){
				expect(await serviceMgmtUtil.getCountFromVerticalBarChart(pervasiveInsightsTestData.monthWiseTrendWidgetName, xAxisLabels[i])).toEqual(countValues[i]);
			}
		});

		it("Elastic validation for 'Week Wise Trend' Wave point graph widget on Pervasive Issue Analysis tab", async function(){
			logger.info("------Week Wise Trend : ES Data validation------");
			await serviceMgmtUtil.clickOnTabLink(pervasiveInsightsTestData.pervasiveIssueAnalysisTabLink);
			// Verify if tab is selected, after clicking on it or not
			await expect(serviceMgmtUtil.isTabLinkSelected(pervasiveInsightsTestData.pervasiveIssueAnalysisTabLink)).toBe(true);
			util.switchToFrameById(frames.cssrIFrame);
			await util.waitForInvisibilityOfKibanaDataLoader();
			var xAxisLabels = await serviceMgmtUtil.getXAxisLabelsFromWaveGraph(pervasiveInsightsTestData.weekWiseTrendWidgetName);
			var weekWiseTrendObjFromES = await esQueriesPervasive.weekWiseTrend(pervasiveInsightsTestData.esPervasiveIndex,tenantId,xAxisLabels);
			expect(await serviceMgmtUtil.verifyCountListWaveGraphPointsFromUIAndESQuery(pervasiveInsightsTestData.weekWiseTrendWidgetName,weekWiseTrendObjFromES)).toBe(true);
		});

		/*it("Elastic validation for 'Pervasive What Time and Day Alert Triggered' heat map filter widget on Pervasive Issue Analysis tab", async function(){
			logger.info("------Pervasive What Time and Day Alert Triggered :ES Data validation------");
			await serviceMgmtUtil.clickOnTabLink(pervasiveInsightsTestData.pervasiveIssueAnalysisTabLink);
			// Verify if tab is selected, after clicking on it or not
			await expect(serviceMgmtUtil.isTabLinkSelected(pervasiveInsightsTestData.pervasiveIssueAnalysisTabLink)).toBe(true);
			util.switchToFrameById(frames.cssrIFrame);
			await util.waitForInvisibilityOfKibanaDataLoader();
			// Get widget JSON Object from ES
			var WhatTimeAndDayAlertTriggerObjFromES = await esQueriesPervasive.timeAndDayAlertTriggered(pervasiveInsightsTestData.esPervasiveIndex,tenantId);
			expect(await serviceMgmtUtil.verifyValuesFromJSONAndUIForHeatMapWidget(pervasiveInsightsTestData.whatTimeDayAlertTriggeredWidgetNameDataTitleName, WhatTimeAndDayAlertTriggerObjFromES)).toBe(true);
		});
		
		it("Elastic validation for 'Top Category View' name map filter widget on Topography tab", async function(){
			logger.info("------Top Category View : ES Data validation------");
			await serviceMgmtUtil.clickOnTabLink(pervasiveInsightsTestData.topographyTabLink);
			// Verify if tab is selected, after clicking on it or not
			await expect(serviceMgmtUtil.isTabLinkSelected(pervasiveInsightsTestData.topographyTabLink)).toBe(true);
			util.switchToFrameById(frames.cssrIFrame);
			await util.waitForInvisibilityOfKibanaDataLoader();
			var topCategoryViewFromWidget = await serviceMgmtUtil.getNamesFromWordCloud(pervasiveInsightsTestData.topCategoryViewWidgetName);
			var filteredTopCategoryViewFromWidget = await util.removeEmptyNullValuesFromList(topCategoryViewFromWidget);
			var topCategoryViewFromES =  await esQueriesPervasive.getTopCategoryView(pervasiveInsightsTestData.esPervasiveIndex, tenantId, 30);
			expect(serviceMgmtUtil.getAllValuesofWordCloudGraph(filteredTopCategoryViewFromWidget,topCategoryViewFromES)).not.toContain("Not-matching");
		});

		it("Elastic validation for 'Category View from Top 10 Address' heat map filter widget on Topography tab", async function(){
			logger.info("------Category View from Top 10 Address : ES Data validation------");
			await serviceMgmtUtil.clickOnTabLink(pervasiveInsightsTestData.topographyTabLink);
			// Verify if tab is selected, after clicking on it or not
			await expect(serviceMgmtUtil.isTabLinkSelected(pervasiveInsightsTestData.topographyTabLink)).toBe(true);
			util.switchToFrameById(frames.cssrIFrame);
			await util.waitForInvisibilityOfKibanaDataLoader();
			var yAxisLabels = await serviceMgmtUtil.getYAxisLabelsListForHeatMapFilter(pervasiveInsightsTestData.categoryViewForTop10AddrWidgetNameDataTitleName);
			var ListOfCountListFromES = await esQueriesPervasive.getCategoryViewForTop10Address(pervasiveInsightsTestData.esPervasiveIndex,tenantId,yAxisLabels);
			var ListOfCountListFromUI = await serviceMgmtUtil.getListOfCountListUsingNameMapWidgetFromHeatMapWidget(pervasiveInsightsTestData.categoryViewForTop10AddrWidgetNameDataTitleName,pervasiveInsightsTestData.topCategoryViewWidgetName,yAxisLabels);
			// Verify the list of list of count values for each row filter from UI with the list of list of count values from ES query response
			expect(util.compareNestedArrays(ListOfCountListFromES, ListOfCountListFromUI)).toBe(true);
		});*/

		it("Validate data Present in 'Site ID Count,Street Address Count, Country View Count' on 'Topography' Tab against elastic", async function(){
			logger.info("-----------Site ID Count,Street Address Count, Country View Count: ES Data Validation------------")
			await serviceMgmtUtil.clickOnTabLink(pervasiveInsightsTestData.topographyTabLink);
			// Verify if tab is selected, after clicking on it or not
			await expect(serviceMgmtUtil.isTabLinkSelected(pervasiveInsightsTestData.topographyTabLink)).toBe(true);
			util.switchToFrameById(frames.cssrIFrame);
			util.waitForInvisibilityOfKibanaDataLoader();
			// Check all widgets on Kibana report are Present
			await expect(serviceMgmtUtil.verifyWidgetNamesPresentOnKibanaReport(topographyTabWidgetNameList)).toBe(true);
			var siteIDCount = await serviceMgmtUtil.getKabianaBoardCardTextBasedOnName(pervasiveInsightsTestData.siteIDCountWidgetName);
			var streetAddrCount = await serviceMgmtUtil.getKabianaBoardCardTextBasedOnName(pervasiveInsightsTestData.streetAddrCountWidgetName);
			var countryViewCount = await serviceMgmtUtil.getKabianaBoardCardTextBasedOnName(pervasiveInsightsTestData.countryViewCountWidgetName);
			// Remove comma (',') from string and convert to integer
			var siteIDCountInt = util.stringToInteger(siteIDCount);
			var streetAddrCountInt = util.stringToInteger(streetAddrCount);
			var countryViewCountInt = util.stringToInteger(countryViewCount);
			logger.info("------ES validation------");
			var siteIDCountFromES = await esQueriesPervasive.siteIDCount(pervasiveInsightsTestData.esPervasiveIndex,tenantId);
	        expect(siteIDCountInt).toEqual(siteIDCountFromES);
			var streetAddrCountFromES = await esQueriesPervasive.streetAddrCount(pervasiveInsightsTestData.esPervasiveIndex,tenantId);
			expect(streetAddrCountInt).toEqual(streetAddrCountFromES);
			var countryViewCountFromES = await esQueriesPervasive.countryViewCount(pervasiveInsightsTestData.esPervasiveIndex,tenantId);
			expect(countryViewCountInt).toEqual(countryViewCountFromES);
		});

		/*it("Elastic validation for BuildingID View on Pervasive topography tab", async function(){
			logger.info("-------BuildingID View: ES Data Validation--------")
			await serviceMgmtUtil.clickOnTabLink(pervasiveInsightsTestData.topographyTabLink);
			// Verify if tab is selected, after clicking on it or not
		    await expect(serviceMgmtUtil.isTabLinkSelected(pervasiveInsightsTestData.topographyTabLink)).toBe(true);
			util.switchToFrameById(frames.cssrIFrame);
			util.waitForInvisibilityOfKibanaDataLoader();
			// Check all widgets on Kibana report are Present
			await expect(serviceMgmtUtil.verifyWidgetNamesPresentOnKibanaReport(topographyTabWidgetNameList)).toBe(true);
			var buildingIDViewObjFromES = await esQueriesPervasive.buildingIDView(pervasiveInsightsTestData.esPervasiveIndex,tenantId);
			logger.info("------ES Data validation------");
			expect(await serviceMgmtUtil.verifyValuesFromJSONAndUIForBoxFilters(pervasiveInsightsTestData.buildingIDViewWidgetNameDataTitleName,buildingIDViewObjFromES)).toBe(true);
		});

		it("Elastic validation for StreetAddress View on Pervasive topography tab", async function(){
			logger.info("-------StreetAddress View: ES Data Validation-------")
			await serviceMgmtUtil.clickOnTabLink(pervasiveInsightsTestData.topographyTabLink);
			// Verify if tab is selected, after clicking on it or not
		    await expect(serviceMgmtUtil.isTabLinkSelected(pervasiveInsightsTestData.topographyTabLink)).toBe(true);
			util.switchToFrameById(frames.cssrIFrame);
			util.waitForInvisibilityOfKibanaDataLoader();
			// Check all widgets on Kibana report are Present
			await expect(serviceMgmtUtil.verifyWidgetNamesPresentOnKibanaReport(topographyTabWidgetNameList)).toBe(true);
			var streetAddrViewObjFromES = await esQueriesPervasive.streetAddrView(pervasiveInsightsTestData.esPervasiveIndex,tenantId);
			logger.info("------ES Data validation------");
			expect(await serviceMgmtUtil.verifyValuesFromJSONAndUIForBoxFilters(pervasiveInsightsTestData.streetAddrViewWidgetName,streetAddrViewObjFromES)).toBe(true);
		});

		it("Elastic validation for siteID View on Pervasive topography tab", async function(){
			logger.info("-----------siteID View: ES Data Validation---------")
			await serviceMgmtUtil.clickOnTabLink(pervasiveInsightsTestData.topographyTabLink);
			// Verify if tab is selected, after clicking on it or not
		    await expect(serviceMgmtUtil.isTabLinkSelected(pervasiveInsightsTestData.topographyTabLink)).toBe(true);
			util.switchToFrameById(frames.cssrIFrame);
			util.waitForInvisibilityOfKibanaDataLoader();
			// Check all widgets on Kibana report are Present
			await expect(serviceMgmtUtil.verifyWidgetNamesPresentOnKibanaReport(topographyTabWidgetNameList)).toBe(true);
			var siteIDViewObjFromES = await esQueriesPervasive.siteIDView(pervasiveInsightsTestData.esPervasiveIndex,tenantId);
			logger.info("------ES Data validation------");
			expect(await serviceMgmtUtil.verifyValuesFromJSONAndUIForBoxFilters(pervasiveInsightsTestData.siteIDViewWidgetNameDataTitleName,siteIDViewObjFromES)).toBe(true);
		});*/


	}

	afterAll(async function() {
		await launchpadObj.clickOnLogoutAndLogin(browser.params.username, browser.params.password);
	});
});
